# Futures data quality: IB API vs DB rolling view

Wraps `scripts/futures_data_quality.py` -- six-step diagnostic:
1. Stale price detection (consecutive zero-return runs)
2. Volume/liquidity gate (if volume available)
3. Roll date contamination (auto-detected or provided)
4. Listwise vs pairwise deletion assessment
5. Covariance matrix comparison (IB pairwise, IB listwise, DB listwise)
6. Structured recommendation

Computation is polars-based throughout. Conversion to pandas happens only
at the `pypfopt.risk_models.sample_cov` call site in Step 5 (consistent
with project CLAUDE.md convention).

Requires a live IB connection for the fetch step.

In [15]:
import sys
import logging
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'scripts' else Path.cwd()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(level=logging.INFO, format='%(levelname)s %(name)s: %(message)s')

import hvplot.polars   # registers .hvplot on polars DataFrames/Series
import polars as pl

from scripts.futures_data_quality import (
    fetch_ib_prices, load_db_prices, run_quality_check
)

pl.Config.set_tbl_rows(1000)
pl.Config.set_tbl_cols(50)
pl.Config.set_fmt_str_lengths(1000)

polars.config.Config

## Parameters — edit here

In [16]:
# Edit INSTRUMENTS to narrow the universe -- delete symbols you don't want.
# INSTRUMENTS = 'MES,MNQ,MCL,MZL,MZC,MZS,MZW,MGC,SIL,J7,BRE,6M'
INSTRUMENTS      = 'ES,NQ'
DURATION         = '3 y'    # IB historical window
INCLUDE_DB       = False    # set True to also load from the local duckdb cache
STALE_THRESHOLD  = 3        # consecutive zero-return days to flag
OUTLIER_SIGMA    = 5.0      # σ for auto roll-date detection
HALFLIFE         = 60.0     # EWM covariance halflife (days)
ROLL_DATES       = None     # dict {ticker: [date_strings]} or None

HOST      = '127.0.0.1'
PORT      = 7496
CLIENT_ID = 22

In [17]:
# Fetch IB data.
from ib_tools.ibpysync import IBPySync
from options_bt.live.run_tsmom_rebalance import KNOWN_INSTRUMENTS, _build_instruments

instruments_spec = globals().get('INSTRUMENTS', ','.join(sorted(KNOWN_INSTRUMENTS)))
instruments = _build_instruments(instruments_spec, None, 15)

print(f'instruments_spec : {instruments_spec!r}')
print(f'instruments ({len(instruments)}):')
for instr in instruments:
    sym      = instr.get('symbol')
    ib_sym   = instr.get('ib_symbol', sym)
    sig_sym  = instr.get('signal_symbol', ib_sym)
    exchange = instr.get('exchange', 'CME')
    print(f'  {sym:8s}  ib={ib_sym}  signal={sig_sym}  exchange={exchange}')

print(f'\nConnecting to IB at {HOST}:{PORT} (clientId={CLIENT_ID}) ...')
ib = IBPySync()
ib.connect(HOST, PORT, CLIENT_ID)
print('Connected.')
try:
    ib_prices, ib_volume = fetch_ib_prices(ib, instruments, duration=DURATION)
except Exception:
    import traceback
    traceback.print_exc()
    raise
finally:
    ib.disconnect()
    print('Disconnected.')

fetched = [c for c in ib_prices.columns if c != 'date']
print(f'\nFetched {len(fetched)}/{len(instruments)} instruments, {len(ib_prices)} rows')
print(f'Columns : {fetched}')
print(f'Volume  : {"yes" if ib_volume is not None else "not available"}')
ib_prices.head()

INFO ib_insync.client: Connecting to 127.0.0.1:7496 with clientId 22...

instruments_spec : 'ES,NQ'
instruments (2):
  ES        ib=ES  signal=ES  exchange=CME
  NQ        ib=NQ  signal=NQ  exchange=CME

Connecting to IB at 127.0.0.1:7496 (clientId=22) ...

INFO ib_insync.client: Connected
INFO ib_insync.client: Logged on to server version 176
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:cafarm
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:hfarm
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:eufarmnj
INFO ib_insync.client: API connection ready
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:usfuture
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:usfuture.nj
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:afarm
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:usopt.nj
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:jfarm
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
INFO ib_insync.wrapper: Warning 2104, reqId -1: Market data farm connection is OK:usfarm
INFO ib_insync.wrapper: Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
INFO ib_insync.wrapper: Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
INFO ib_insync.wrapper: Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
INFO ib_insync.wrapper: Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefil
INFO ib_insync.wrapper: position: Position(account='U19484184', contract=Future(conId=793356217, symbol='MES', lastTradeDateOrContractMonth='20260918', multiplier='5', currency='USD', localSymbol='MESU6', tradingClass='MES'), position=1.0, avgCost=38240.62)
INFO ib_insync.wrapper: position: Position(account='U14192638', contract=Future(conId=793356217, symbol='MES', lastTradeDateOrContractMonth='20260918', multiplier='5', currency='USD', localSymbol='MESU6', tradingClass='MES'), position=1.0, avgCost=38239.37)
INFO ib_insync.wrapper: position: Position(account='U19484184', contract=Future(conId=666754638, symbol='MCL', lastTradeDateOrContractMonth='20261218', multiplier='100', currency='USD', localSymbol='MCLF7', tradingClass='MCL'), position=2.0, avgCost=7903.77)
INFO ib_insync.wrapper: position: Position(account='U14192638', contract=Future(conId=666754638, symbol='MCL', lastTradeDateOrContractMonth='20261218', multiplier='100', currency='USD', localSymbol='MCLF7', tradingClass='MCL'), position=2.0, avgCost=7864.77)
INFO ib_insync.wrapper: position: Position(account='U19484184', contract=Future(conId=661016537, symbol='MCL', lastTradeDateOrContractMonth='20260720', multiplier='100', currency='USD', localSymbol='MCLQ6', tradingClass='MCL'), position=1.0, avgCost=8400.77)
INFO ib_insync.wrapper: position: Position(account='U14192638', contract=Future(conId=661016537, symbol='MCL', lastTradeDateOrContractMonth='20260720', multiplier='100', currency='USD', localSymbol='MCLQ6', tradingClass='MCL'), position=1.0, avgCost=8400.77)
INFO ib_insync.ib: Synchronization complete
INFO scripts.futures_data_quality: ES: qualifying contract (ES @ CME)...

Connected.

INFO scripts.futures_data_quality: ES: fetching ES continuous bars...
INFO scripts.futures_data_quality: NQ: qualifying contract (NQ @ CME)...
INFO scripts.futures_data_quality: NQ: fetching NQ continuous bars...
INFO ib_insync.ib: Disconnecting from 127.0.0.1:7496, 396 B sent in 12 messages, 129 kB received in 392 messages, session time 8.69 s.
INFO ib_insync.client: Disconnecting
INFO ib_insync.client: Disconnected.

Disconnected.

Fetched 2/2 instruments, 748 rows
Columns : ['ES', 'NQ']
Volume  : yes

shape: (5, 3)
┌────────────┬─────────┬──────────┐
│ date       ┆ ES      ┆ NQ       │
│ ---        ┆ ---     ┆ ---      │
│ date       ┆ f64     ┆ f64      │
╞════════════╪═════════╪══════════╡
│ 2023-07-05 ┆ 5036.0  ┆ 17564.0  │
│ 2023-07-06 ┆ 4996.25 ┆ 17430.25 │
│ 2023-07-07 ┆ 4982.25 ┆ 17368.25 │
│ 2023-07-10 ┆ 4992.0  ┆ 17353.0  │
│ 2023-07-11 ┆ 5024.25 ┆ 17429.0  │
└────────────┴─────────┴──────────┘

In [18]:
ib_volume

shape: (748, 3)
┌────────────┬────────────┬──────────┐
│ date       ┆ ES         ┆ NQ       │
│ ---        ┆ ---        ┆ ---      │
│ date       ┆ f64        ┆ f64      │
╞════════════╪════════════╪══════════╡
│ 2023-07-05 ┆ 0.0        ┆ 0.0      │
│ 2023-07-06 ┆ 0.0        ┆ 0.0      │
│ 2023-07-07 ┆ 0.0        ┆ 0.0      │
│ 2023-07-10 ┆ 0.0        ┆ 0.0      │
│ 2023-07-11 ┆ 0.0        ┆ 0.0      │
│ 2023-07-12 ┆ 0.0        ┆ 0.0      │
│ 2023-07-13 ┆ 0.0        ┆ 0.0      │
│ 2023-07-14 ┆ 0.0        ┆ 0.0      │
│ 2023-07-17 ┆ 0.0        ┆ 0.0      │
│ 2023-07-18 ┆ 0.0        ┆ 0.0      │
│ 2023-07-19 ┆ 0.0        ┆ 0.0      │
│ 2023-07-20 ┆ 0.0        ┆ 0.0      │
│ 2023-07-21 ┆ 0.0        ┆ 0.0      │
│ 2023-07-24 ┆ 0.0        ┆ 0.0      │
│ 2023-07-25 ┆ 0.0        ┆ 0.0      │
│ 2023-07-26 ┆ 0.0        ┆ 0.0      │
│ 2023-07-27 ┆ 0.0        ┆ 0.0      │
│ 2023-07-28 ┆ 0.0        ┆ 0.0      │
│ 2023-07-31 ┆ 0.0        ┆ 0.0      │
│ 2023-08-01 ┆ 0.0        ┆ 0.0      │
│ 2023-08-02 ┆ 0.0        ┆ 0.0      │
│ 2023-08-03 ┆ 0.0        ┆ 0.0      │
│ 2023-08-04 ┆ 0.0        ┆ 0.0      │
│ 2023-08-07 ┆ 0.0        ┆ 0.0      │
│ 2023-08-08 ┆ 0.0        ┆ 0.0      │
│ 2023-08-09 ┆ 0.0        ┆ 0.0      │
│ 2023-08-10 ┆ 0.0        ┆ 0.0      │
│ 2023-08-11 ┆ 0.0        ┆ 0.0      │
│ 2023-08-14 ┆ 0.0        ┆ 0.0      │
│ 2023-08-15 ┆ 0.0        ┆ 0.0      │
│ 2023-08-16 ┆ 0.0        ┆ 0.0      │
│ 2023-08-17 ┆ 0.0        ┆ 0.0      │
│ 2023-08-18 ┆ 0.0        ┆ 0.0      │
│ 2023-08-21 ┆ 0.0        ┆ 0.0      │
│ 2023-08-22 ┆ 0.0        ┆ 0.0      │
│ 2023-08-23 ┆ 0.0        ┆ 0.0      │
│ 2023-08-24 ┆ 0.0        ┆ 0.0      │
│ 2023-08-25 ┆ 1.0        ┆ 0.0      │
│ 2023-08-28 ┆ 0.0        ┆ 0.0      │
│ 2023-08-29 ┆ 3.0        ┆ 0.0      │
│ 2023-08-30 ┆ 2.0        ┆ 0.0      │
│ 2023-08-31 ┆ 1.0        ┆ 0.0      │
│ 2023-09-01 ┆ 0.0        ┆ 0.0      │
│ 2023-09-05 ┆ 0.0        ┆ 0.0      │
│ 2023-09-06 ┆ 0.0        ┆ 0.0      │
│ 2023-09-07 ┆ 0.0        ┆ 0.0      │
│ 2023-09-08 ┆ 0.0        ┆ 0.0      │
│ 2023-09-11 ┆ 0.0        ┆ 0.0      │
│ 2023-09-12 ┆ 2.0        ┆ 0.0      │
│ 2023-09-13 ┆ 0.0        ┆ 0.0      │
│ 2023-09-14 ┆ 1.0        ┆ 0.0      │
│ 2023-09-15 ┆ 0.0        ┆ 0.0      │
│ 2023-09-18 ┆ 0.0        ┆ 0.0      │
│ 2023-09-19 ┆ 2.0        ┆ 0.0      │
│ 2023-09-20 ┆ 2.0        ┆ 0.0      │
│ 2023-09-21 ┆ 3.0        ┆ 1.0      │
│ 2023-09-22 ┆ 0.0        ┆ 1.0      │
│ 2023-09-25 ┆ 0.0        ┆ 0.0      │
│ 2023-09-26 ┆ 18.0       ┆ 0.0      │
│ 2023-09-27 ┆ 3.0        ┆ 0.0      │
│ 2023-09-28 ┆ 0.0        ┆ 10.0     │
│ 2023-09-29 ┆ 18.0       ┆ 0.0      │
│ 2023-10-02 ┆ 1.0        ┆ 0.0      │
│ 2023-10-03 ┆ 0.0        ┆ 1.0      │
│ 2023-10-04 ┆ 2.0        ┆ 0.0      │
│ 2023-10-05 ┆ 19.0       ┆ 0.0      │
│ 2023-10-06 ┆ 2.0        ┆ 0.0      │
│ 2023-10-09 ┆ 1.0        ┆ 0.0      │
│ 2023-10-10 ┆ 3.0        ┆ 0.0      │
│ 2023-10-11 ┆ 1.0        ┆ 0.0      │
│ 2023-10-12 ┆ 0.0        ┆ 0.0      │
│ 2023-10-13 ┆ 0.0        ┆ 1.0      │
│ 2023-10-16 ┆ 0.0        ┆ 0.0      │
│ 2023-10-17 ┆ 0.0        ┆ 0.0      │
│ 2023-10-18 ┆ 0.0        ┆ 0.0      │
│ 2023-10-19 ┆ 0.0        ┆ 0.0      │
│ 2023-10-20 ┆ 2.0        ┆ 0.0      │
│ 2023-10-23 ┆ 12.0       ┆ 0.0      │
│ 2023-10-24 ┆ 1.0        ┆ 0.0      │
│ 2023-10-25 ┆ 2.0        ┆ 0.0      │
│ 2023-10-26 ┆ 0.0        ┆ 0.0      │
│ 2023-10-27 ┆ 3.0        ┆ 0.0      │
│ 2023-10-30 ┆ 3.0        ┆ 0.0      │
│ 2023-10-31 ┆ 0.0        ┆ 0.0      │
│ 2023-11-01 ┆ 3.0        ┆ 1.0      │
│ 2023-11-02 ┆ 6.0        ┆ 0.0      │
│ 2023-11-03 ┆ 2.0        ┆ 0.0      │
│ 2023-11-06 ┆ 1.0        ┆ 0.0      │
│ 2023-11-07 ┆ 5.0        ┆ 0.0      │
│ 2023-11-08 ┆ 1.0        ┆ 0.0      │
│ 2023-11-09 ┆ 1.0        ┆ 0.0      │
│ 2023-11-10 ┆ 2.0        ┆ 0.0      │
│ 2023-11-13 ┆ 0.0        ┆ 0.0      │
│ 2023-11-14 ┆ 1.0        ┆ 0.0      │
│ 2023-11-15 ┆ 2.0        ┆ 0.0      │
│ 2023-11-16 ┆ 0.0        ┆ 0.0      │
│ 2023-11-17 ┆ 3.0        ┆ 0.0      │
│ 2023-11-20 ┆ 4.0        ┆ 0.0      │
│ 2023-11-21 ┆ 0.0        ┆ 0.0      │
│ 2023-11-22 ┆ 3.0        ┆ 0.0      │
│ 2023-11-24 ┆ 2.0        ┆ 0.0      │
│ 2023-11-27 ┆ 0.0        ┆ 0.0      │
│ 2023-11-28 ┆ 2.0        ┆ 0.0      │
│ 2023-11-29 ┆ 5.0        ┆ 0.0      │
│ 2023-11-30 ┆ 2.0        ┆ 0.0      │
│ 2023-12-01 ┆ 1.0        ┆ 0.0      │
│ 2023-12-04 ┆ 1.0        ┆ 0.0      │
│ 2023-12-05 ┆ 0.0        ┆ 0.0      │
│ 2023-12-06 ┆ 1.0        ┆ 0.0      │
│ 2023-12-07 ┆ 0.0        ┆ 0.0      │
│ 2023-12-08 ┆ 2.0        ┆ 0.0      │
│ 2023-12-11 ┆ 2.0        ┆ 0.0      │
│ 2023-12-12 ┆ 3.0        ┆ 0.0      │
│ 2023-12-13 ┆ 11.0       ┆ 1.0      │
│ 2023-12-14 ┆ 4.0        ┆ 0.0      │
│ 2023-12-15 ┆ 2.0        ┆ 0.0      │
│ 2023-12-18 ┆ 6.0        ┆ 0.0      │
│ 2023-12-19 ┆ 6.0        ┆ 1.0      │
│ 2023-12-20 ┆ 12.0       ┆ 2.0      │
│ 2023-12-21 ┆ 10.0       ┆ 0.0      │
│ 2023-12-22 ┆ 2.0        ┆ 0.0      │
│ 2023-12-26 ┆ 4.0        ┆ 1.0      │
│ 2023-12-27 ┆ 4.0        ┆ 0.0      │
│ 2023-12-28 ┆ 14.0       ┆ 1.0      │
│ 2023-12-29 ┆ 2.0        ┆ 1.0      │
│ 2024-01-02 ┆ 2.0        ┆ 0.0      │
│ 2024-01-03 ┆ 3.0        ┆ 0.0      │
│ 2024-01-08 ┆ 3.0        ┆ 2.0      │
│ 2024-01-09 ┆ 1.0        ┆ 1.0      │
│ 2024-01-11 ┆ 19.0       ┆ 2.0      │
│ 2024-01-12 ┆ 4.0        ┆ 2.0      │
│ 2024-01-16 ┆ 23.0       ┆ 0.0      │
│ 2024-01-17 ┆ 2.0        ┆ 4.0      │
│ 2024-01-18 ┆ 114.0      ┆ 3.0      │
│ 2024-01-19 ┆ 333.0      ┆ 9.0      │
│ 2024-01-22 ┆ 23.0       ┆ 0.0      │
│ 2024-01-23 ┆ 19.0       ┆ 0.0      │
│ 2024-01-24 ┆ 25.0       ┆ 1.0      │
│ 2024-01-25 ┆ 142.0      ┆ 3.0      │
│ 2024-01-26 ┆ 17.0       ┆ 17.0     │
│ 2024-01-29 ┆ 88.0       ┆ 2.0      │
│ 2024-01-30 ┆ 13.0       ┆ 4.0      │
│ 2024-01-31 ┆ 39.0       ┆ 4.0      │
│ 2024-02-01 ┆ 24.0       ┆ 3.0      │
│ 2024-02-02 ┆ 53.0       ┆ 14.0     │
│ 2024-02-05 ┆ 68.0       ┆ 2.0      │
│ 2024-02-06 ┆ 20.0       ┆ 1.0      │
│ 2024-02-07 ┆ 15.0       ┆ 5.0      │
│ 2024-02-08 ┆ 4.0        ┆ 0.0      │
│ 2024-02-09 ┆ 31.0       ┆ 2.0      │
│ 2024-02-12 ┆ 24.0       ┆ 6.0      │
│ 2024-02-13 ┆ 17.0       ┆ 12.0     │
│ 2024-02-14 ┆ 57.0       ┆ 7.0      │
│ 2024-02-15 ┆ 40.0       ┆ 8.0      │
│ 2024-02-16 ┆ 51.0       ┆ 2.0      │
│ 2024-02-20 ┆ 19.0       ┆ 8.0      │
│ 2024-02-21 ┆ 20.0       ┆ 5.0      │
│ 2024-02-22 ┆ 74.0       ┆ 10.0     │
│ 2024-02-23 ┆ 62.0       ┆ 6.0      │
│ 2024-02-26 ┆ 23.0       ┆ 12.0     │
│ 2024-02-27 ┆ 16.0       ┆ 4.0      │
│ 2024-02-28 ┆ 19.0       ┆ 14.0     │
│ 2024-02-29 ┆ 50.0       ┆ 15.0     │
│ 2024-03-01 ┆ 122.0      ┆ 22.0     │
│ 2024-03-04 ┆ 77.0       ┆ 39.0     │
│ 2024-03-05 ┆ 55.0       ┆ 59.0     │
│ 2024-03-06 ┆ 79.0       ┆ 18.0     │
│ 2024-03-07 ┆ 152.0      ┆ 58.0     │
│ 2024-03-08 ┆ 134.0      ┆ 54.0     │
│ 2024-03-11 ┆ 123.0      ┆ 46.0     │
│ 2024-03-12 ┆ 290.0      ┆ 278.0    │
│ 2024-03-13 ┆ 1294.0     ┆ 48.0     │
│ 2024-03-14 ┆ 416.0      ┆ 145.0    │
│ 2024-03-15 ┆ 756.0      ┆ 516.0    │
│ 2024-03-18 ┆ 472.0      ┆ 349.0    │
│ 2024-03-19 ┆ 399.0      ┆ 459.0    │
│ 2024-03-20 ┆ 1010.0     ┆ 615.0    │
│ 2024-03-21 ┆ 370.0      ┆ 384.0    │
│ 2024-03-22 ┆ 274.0      ┆ 113.0    │
│ 2024-03-25 ┆ 232.0      ┆ 159.0    │
│ 2024-03-26 ┆ 258.0      ┆ 119.0    │
│ 2024-03-27 ┆ 459.0      ┆ 298.0    │
│ 2024-03-28 ┆ 375.0      ┆ 241.0    │
│ 2024-04-01 ┆ 386.0      ┆ 154.0    │
│ 2024-04-02 ┆ 413.0      ┆ 171.0    │
│ 2024-04-03 ┆ 419.0      ┆ 281.0    │
│ 2024-04-04 ┆ 698.0      ┆ 552.0    │
│ 2024-04-05 ┆ 683.0      ┆ 364.0    │
│ 2024-04-08 ┆ 253.0      ┆ 155.0    │
│ 2024-04-09 ┆ 540.0      ┆ 307.0    │
│ 2024-04-10 ┆ 825.0      ┆ 546.0    │
│ 2024-04-11 ┆ 710.0      ┆ 463.0    │
│ 2024-04-12 ┆ 889.0      ┆ 442.0    │
│ 2024-04-15 ┆ 891.0      ┆ 797.0    │
│ 2024-04-16 ┆ 787.0      ┆ 623.0    │
│ 2024-04-17 ┆ 1309.0     ┆ 640.0    │
│ 2024-04-18 ┆ 1008.0     ┆ 680.0    │
│ 2024-04-19 ┆ 881.0      ┆ 846.0    │
│ 2024-04-22 ┆ 556.0      ┆ 555.0    │
│ 2024-04-23 ┆ 519.0      ┆ 438.0    │
│ 2024-04-24 ┆ 533.0      ┆ 309.0    │
│ 2024-04-25 ┆ 688.0      ┆ 486.0    │
│ 2024-04-26 ┆ 642.0      ┆ 407.0    │
│ 2024-04-29 ┆ 242.0      ┆ 163.0    │
│ 2024-04-30 ┆ 448.0      ┆ 406.0    │
│ 2024-05-01 ┆ 1002.0     ┆ 785.0    │
│ 2024-05-02 ┆ 622.0      ┆ 532.0    │
│ 2024-05-03 ┆ 903.0      ┆ 627.0    │
│ 2024-05-06 ┆ 390.0      ┆ 411.0    │
│ 2024-05-07 ┆ 388.0      ┆ 341.0    │
│ 2024-05-08 ┆ 295.0      ┆ 245.0    │
│ 2024-05-09 ┆ 427.0      ┆ 246.0    │
│ 2024-05-10 ┆ 568.0      ┆ 413.0    │
│ 2024-05-13 ┆ 225.0      ┆ 535.0    │
│ 2024-05-14 ┆ 862.0      ┆ 610.0    │
│ 2024-05-15 ┆ 1514.0     ┆ 760.0    │
│ 2024-05-16 ┆ 779.0      ┆ 359.0    │
│ 2024-05-17 ┆ 323.0      ┆ 280.0    │
│ 2024-05-20 ┆ 401.0      ┆ 452.0    │
│ 2024-05-21 ┆ 424.0      ┆ 422.0    │
│ 2024-05-22 ┆ 1091.0     ┆ 675.0    │
│ 2024-05-23 ┆ 1817.0     ┆ 1143.0   │
│ 2024-05-24 ┆ 1200.0     ┆ 601.0    │
│ 2024-05-28 ┆ 1117.0     ┆ 583.0    │
│ 2024-05-29 ┆ 1079.0     ┆ 993.0    │
│ 2024-05-30 ┆ 2483.0     ┆ 947.0    │
│ 2024-05-31 ┆ 3564.0     ┆ 1645.0   │
│ 2024-06-03 ┆ 3139.0     ┆ 1334.0   │
│ 2024-06-04 ┆ 7723.0     ┆ 1922.0   │
│ 2024-06-05 ┆ 7783.0     ┆ 2499.0   │
│ 2024-06-06 ┆ 5694.0     ┆ 1703.0   │
│ 2024-06-07 ┆ 10210.0    ┆ 3593.0   │
│ 2024-06-10 ┆ 7219.0     ┆ 2628.0   │
│ 2024-06-11 ┆ 13276.0    ┆ 4397.0   │
│ 2024-06-12 ┆ 38212.0    ┆ 12385.0  │
│ 2024-06-13 ┆ 162624.0   ┆ 55714.0  │
│ 2024-06-14 ┆ 314706.0   ┆ 136403.0 │
│ 2024-06-17 ┆ 911847.0   ┆ 439542.0 │
│ 2024-06-18 ┆ 826651.0   ┆ 401024.0 │
│ 2024-06-20 ┆ 1.25167e6  ┆ 676527.0 │
│ 2024-06-21 ┆ 1.042563e6 ┆ 458014.0 │
│ 2024-06-24 ┆ 1.172557e6 ┆ 570927.0 │
│ 2024-06-25 ┆ 901562.0   ┆ 464066.0 │
│ 2024-06-26 ┆ 928999.0   ┆ 469909.0 │
│ 2024-06-27 ┆ 1.016008e6 ┆ 489116.0 │
│ 2024-06-28 ┆ 1.497621e6 ┆ 626879.0 │
│ 2024-07-01 ┆ 1.153785e6 ┆ 516718.0 │
│ 2024-07-02 ┆ 1.043401e6 ┆ 503305.0 │
│ 2024-07-03 ┆ 580493.0   ┆ 305547.0 │
│ 2024-07-05 ┆ 884456.0   ┆ 450622.0 │
│ 2024-07-08 ┆ 781998.0   ┆ 417753.0 │
│ 2024-07-09 ┆ 880100.0   ┆ 475745.0 │
│ 2024-07-10 ┆ 994486.0   ┆ 496841.0 │
│ 2024-07-11 ┆ 1.647027e6 ┆ 764887.0 │
│ 2024-07-12 ┆ 1.403663e6 ┆ 594617.0 │
│ 2024-07-15 ┆ 1.471477e6 ┆ 604003.0 │
│ 2024-07-16 ┆ 1.262672e6 ┆ 532302.0 │
│ 2024-07-17 ┆ 1.705285e6 ┆ 672653.0 │
│ 2024-07-18 ┆ 2.210024e6 ┆ 803795.0 │
│ 2024-07-19 ┆ 1.736154e6 ┆ 615341.0 │
│ 2024-07-22 ┆ 1.390992e6 ┆ 511892.0 │
│ 2024-07-23 ┆ 1.164456e6 ┆ 485812.0 │
│ 2024-07-24 ┆ 1.800177e6 ┆ 661714.0 │
│ 2024-07-25 ┆ 2.357403e6 ┆ 763298.0 │
│ 2024-07-26 ┆ 1.671687e6 ┆ 568579.0 │
│ 2024-07-29 ┆ 1.453176e6 ┆ 483022.0 │
│ 2024-07-30 ┆ 1.828945e6 ┆ 644944.0 │
│ 2024-07-31 ┆ 1.723161e6 ┆ 580690.0 │
│ 2024-08-01 ┆ 2.369701e6 ┆ 736265.0 │
│ 2024-08-02 ┆ 2.576469e6 ┆ 616905.0 │
│ 2024-08-05 ┆ 2.313948e6 ┆ 599809.0 │
│ 2024-08-06 ┆ 1.682901e6 ┆ 522515.0 │
│ 2024-08-07 ┆ 1.810284e6 ┆ 572603.0 │
│ 2024-08-08 ┆ 1.448033e6 ┆ 494266.0 │
│ 2024-08-09 ┆ 1.104669e6 ┆ 371635.0 │
│ 2024-08-12 ┆ 1.040041e6 ┆ 392161.0 │
│ 2024-08-13 ┆ 995830.0   ┆ 378468.0 │
│ 2024-08-14 ┆ 1.033172e6 ┆ 435211.0 │
│ 2024-08-15 ┆ 1.091257e6 ┆ 400781.0 │
│ 2024-08-16 ┆ 810910.0   ┆ 336277.0 │
│ 2024-08-19 ┆ 788094.0   ┆ 346846.0 │
│ 2024-08-20 ┆ 852228.0   ┆ 401311.0 │
│ 2024-08-21 ┆ 915179.0   ┆ 409042.0 │
│ 2024-08-22 ┆ 1.228777e6 ┆ 551371.0 │
│ 2024-08-23 ┆ 1.230698e6 ┆ 507254.0 │
│ 2024-08-26 ┆ 941294.0   ┆ 394409.0 │
│ 2024-08-27 ┆ 822964.0   ┆ 349815.0 │
│ 2024-08-28 ┆ 1.192928e6 ┆ 460001.0 │
│ 2024-08-29 ┆ 1.294367e6 ┆ 520493.0 │
│ 2024-08-30 ┆ 1.307103e6 ┆ 405296.0 │
│ 2024-09-03 ┆ 1.508785e6 ┆ 504279.0 │
│ 2024-09-04 ┆ 1.400451e6 ┆ 443141.0 │
│ 2024-09-05 ┆ 1.435434e6 ┆ 457910.0 │
│ 2024-09-06 ┆ 1.877364e6 ┆ 560055.0 │
│ 2024-09-09 ┆ 1.272609e6 ┆ 415869.0 │
│ 2024-09-10 ┆ 1.237367e6 ┆ 426980.0 │
│ 2024-09-11 ┆ 1.858245e6 ┆ 579602.0 │
│ 2024-09-12 ┆ 1.296528e6 ┆ 448670.0 │
│ 2024-09-13 ┆ 911767.0   ┆ 350875.0 │
│ 2024-09-16 ┆ 384438.0   ┆ 182037.0 │
│ 2024-09-17 ┆ 994101.0   ┆ 342243.0 │
│ 2024-09-18 ┆ 1.336663e6 ┆ 444966.0 │
│ 2024-09-19 ┆ 1.201026e6 ┆ 418148.0 │
│ 2024-09-20 ┆ 1.222253e6 ┆ 375943.0 │
│ 2024-09-23 ┆ 849859.0   ┆ 298718.0 │
│ 2024-09-24 ┆ 949145.0   ┆ 361070.0 │
│ 2024-09-25 ┆ 848693.0   ┆ 326136.0 │
│ 2024-09-26 ┆ 1.060948e6 ┆ 392422.0 │
│ 2024-09-27 ┆ 989526.0   ┆ 329755.0 │
│ 2024-09-30 ┆ 1.177744e6 ┆ 413095.0 │
│ 2024-10-01 ┆ 1.713821e6 ┆ 571593.0 │
│ 2024-10-02 ┆ 982650.0   ┆ 368623.0 │
│ 2024-10-03 ┆ 1.157919e6 ┆ 420195.0 │
│ 2024-10-04 ┆ 1.126816e6 ┆ 430570.0 │
│ 2024-10-07 ┆ 939444.0   ┆ 343770.0 │
│ 2024-10-08 ┆ 853947.0   ┆ 332850.0 │
│ 2024-10-09 ┆ 924305.0   ┆ 340185.0 │
│ 2024-10-10 ┆ 849766.0   ┆ 351431.0 │
│ 2024-10-11 ┆ 831774.0   ┆ 306211.0 │
│ 2024-10-14 ┆ 730147.0   ┆ 316467.0 │
│ 2024-10-15 ┆ 1.141292e6 ┆ 442272.0 │
│ 2024-10-16 ┆ 758617.0   ┆ 336934.0 │
│ 2024-10-17 ┆ 970596.0   ┆ 415898.0 │
│ 2024-10-18 ┆ 730385.0   ┆ 298741.0 │
│ 2024-10-21 ┆ 900472.0   ┆ 368435.0 │
│ 2024-10-22 ┆ 824014.0   ┆ 363847.0 │
│ 2024-10-23 ┆ 1.270217e6 ┆ 527838.0 │
│ 2024-10-24 ┆ 967719.0   ┆ 369628.0 │
│ 2024-10-25 ┆ 1.166199e6 ┆ 491757.0 │
│ 2024-10-28 ┆ 782339.0   ┆ 325823.0 │
│ 2024-10-29 ┆ 951328.0   ┆ 400829.0 │
│ 2024-10-30 ┆ 1.063978e6 ┆ 407072.0 │
│ 2024-10-31 ┆ 1.594014e6 ┆ 550193.0 │
│ 2024-11-01 ┆ 1.259321e6 ┆ 439610.0 │
│ 2024-11-04 ┆ 1.062278e6 ┆ 394250.0 │
│ 2024-11-05 ┆ 998048.0   ┆ 368942.0 │
│ 2024-11-06 ┆ 1.279628e6 ┆ 417766.0 │
│ 2024-11-07 ┆ 1.004076e6 ┆ 362980.0 │
│ 2024-11-08 ┆ 885614.0   ┆ 303904.0 │
│ 2024-11-11 ┆ 848998.0   ┆ 364939.0 │
│ 2024-11-12 ┆ 1.123146e6 ┆ 398904.0 │
│ 2024-11-13 ┆ 1.125095e6 ┆ 420893.0 │
│ 2024-11-14 ┆ 1.276933e6 ┆ 450098.0 │
│ 2024-11-15 ┆ 1.541557e6 ┆ 544312.0 │
│ 2024-11-18 ┆ 1.027548e6 ┆ 380041.0 │
│ 2024-11-19 ┆ 1.15842e6  ┆ 371061.0 │
│ 2024-11-20 ┆ 1.326865e6 ┆ 499300.0 │
│ 2024-11-21 ┆ 1.476163e6 ┆ 521848.0 │
│ 2024-11-22 ┆ 1.244348e6 ┆ 416783.0 │
│ 2024-11-25 ┆ 1.333989e6 ┆ 438923.0 │
│ 2024-11-26 ┆ 988177.0   ┆ 370746.0 │
│ 2024-11-27 ┆ 922681.0   ┆ 423341.0 │
│ 2024-11-29 ┆ 564144.0   ┆ 206169.0 │
│ 2024-12-02 ┆ 773527.0   ┆ 387594.0 │
│ 2024-12-03 ┆ 786529.0   ┆ 361173.0 │
│ 2024-12-04 ┆ 902562.0   ┆ 364493.0 │
│ 2024-12-05 ┆ 921302.0   ┆ 349153.0 │
│ 2024-12-06 ┆ 915367.0   ┆ 367453.0 │
│ 2024-12-09 ┆ 1.126732e6 ┆ 418137.0 │
│ 2024-12-10 ┆ 1.105302e6 ┆ 461028.0 │
│ 2024-12-11 ┆ 990655.0   ┆ 445739.0 │
│ 2024-12-12 ┆ 1.152801e6 ┆ 401205.0 │
│ 2024-12-13 ┆ 1.027682e6 ┆ 466826.0 │
│ 2024-12-16 ┆ 378263.0   ┆ 241512.0 │
│ 2024-12-17 ┆ 997849.0   ┆ 379533.0 │
│ 2024-12-18 ┆ 2.009987e6 ┆ 565684.0 │
│ 2024-12-19 ┆ 1.716173e6 ┆ 528702.0 │
│ 2024-12-20 ┆ 1.720536e6 ┆ 630078.0 │
│ 2024-12-23 ┆ 1.102408e6 ┆ 388158.0 │
│ 2024-12-24 ┆ 497383.0   ┆ 199454.0 │
│ 2024-12-26 ┆ 724353.0   ┆ 315494.0 │
│ 2024-12-27 ┆ 1.411128e6 ┆ 489320.0 │
│ 2024-12-30 ┆ 1.282058e6 ┆ 403585.0 │
│ 2024-12-31 ┆ 1.142781e6 ┆ 390822.0 │
│ 2025-01-02 ┆ 1.496415e6 ┆ 509606.0 │
│ 2025-01-03 ┆ 1.009229e6 ┆ 394885.0 │
│ 2025-01-06 ┆ 1.207465e6 ┆ 433696.0 │
│ 2025-01-07 ┆ 1.543464e6 ┆ 540572.0 │
│ 2025-01-08 ┆ 1.436052e6 ┆ 473334.0 │
│ 2025-01-10 ┆ 1.696137e6 ┆ 537724.0 │
│ 2025-01-13 ┆ 1.420722e6 ┆ 446493.0 │
│ 2025-01-14 ┆ 1.525051e6 ┆ 522664.0 │
│ 2025-01-15 ┆ 1.256322e6 ┆ 423599.0 │
│ 2025-01-16 ┆ 1.268023e6 ┆ 456218.0 │
│ 2025-01-17 ┆ 1.082378e6 ┆ 444142.0 │
│ 2025-01-21 ┆ 1.111808e6 ┆ 390335.0 │
│ 2025-01-22 ┆ 987097.0   ┆ 400028.0 │
│ 2025-01-23 ┆ 917464.0   ┆ 376022.0 │
│ 2025-01-24 ┆ 1.017586e6 ┆ 390449.0 │
│ 2025-01-27 ┆ 1.688106e6 ┆ 644920.0 │
│ 2025-01-28 ┆ 1.27936e6  ┆ 503276.0 │
│ 2025-01-29 ┆ 1.342474e6 ┆ 523392.0 │
│ 2025-01-30 ┆ 1.370253e6 ┆ 502110.0 │
│ 2025-01-31 ┆ 1.609577e6 ┆ 545134.0 │
│ 2025-02-03 ┆ 1.710269e6 ┆ 529402.0 │
│ 2025-02-04 ┆ 1.012513e6 ┆ 375872.0 │
│ 2025-02-05 ┆ 956301.0   ┆ 377548.0 │
│ 2025-02-06 ┆ 962902.0   ┆ 351797.0 │
│ 2025-02-07 ┆ 1.463511e6 ┆ 510061.0 │
│ 2025-02-10 ┆ 799826.0   ┆ 294062.0 │
│ 2025-02-11 ┆ 832687.0   ┆ 329733.0 │
│ 2025-02-12 ┆ 1.208683e6 ┆ 410403.0 │
│ 2025-02-13 ┆ 1.250351e6 ┆ 418596.0 │
│ 2025-02-14 ┆ 800631.0   ┆ 341251.0 │
│ 2025-02-18 ┆ 923879.0   ┆ 374804.0 │
│ 2025-02-19 ┆ 879970.0   ┆ 399925.0 │
│ 2025-02-20 ┆ 1.205593e6 ┆ 476740.0 │
│ 2025-02-21 ┆ 1.691282e6 ┆ 614803.0 │
│ 2025-02-24 ┆ 1.504553e6 ┆ 551277.0 │
│ 2025-02-25 ┆ 1.864021e6 ┆ 646535.0 │
│ 2025-02-26 ┆ 1.644114e6 ┆ 545198.0 │
│ 2025-02-27 ┆ 2.198039e6 ┆ 694457.0 │
│ 2025-02-28 ┆ 2.339831e6 ┆ 683202.0 │
│ 2025-03-03 ┆ 2.229904e6 ┆ 685573.0 │
│ 2025-03-04 ┆ 2.787467e6 ┆ 742066.0 │
│ 2025-03-05 ┆ 1.81803e6  ┆ 619208.0 │
│ 2025-03-06 ┆ 2.155366e6 ┆ 613987.0 │
│ 2025-03-07 ┆ 1.865646e6 ┆ 615413.0 │
│ 2025-03-10 ┆ 2.068527e6 ┆ 621572.0 │
│ 2025-03-11 ┆ 2.072069e6 ┆ 642756.0 │
│ 2025-03-12 ┆ 1.513476e6 ┆ 539929.0 │
│ 2025-03-13 ┆ 1.561729e6 ┆ 561496.0 │
│ 2025-03-14 ┆ 1.30764e6  ┆ 535514.0 │
│ 2025-03-17 ┆ 554842.0   ┆ 306099.0 │
│ 2025-03-18 ┆ 1.012705e6 ┆ 177296.0 │
│ 2025-03-19 ┆ 1.161071e6 ┆ 419894.0 │
│ 2025-03-20 ┆ 1.262796e6 ┆ 444527.0 │
│ 2025-03-21 ┆ 1.214828e6 ┆ 468697.0 │
│ 2025-03-24 ┆ 1.106689e6 ┆ 409313.0 │
│ 2025-03-25 ┆ 842430.0   ┆ 369721.0 │
│ 2025-03-26 ┆ 1.269497e6 ┆ 533050.0 │
│ 2025-03-27 ┆ 1.287285e6 ┆ 495099.0 │
│ 2025-03-28 ┆ 1.595221e6 ┆ 564524.0 │
│ 2025-03-31 ┆ 1.766518e6 ┆ 641559.0 │
│ 2025-04-01 ┆ 1.521047e6 ┆ 634848.0 │
│ 2025-04-02 ┆ 1.731713e6 ┆ 696313.0 │
│ 2025-04-03 ┆ 1.823498e6 ┆ 642714.0 │
│ 2025-04-04 ┆ 2.588168e6 ┆ 900886.0 │
│ 2025-04-07 ┆ 2.426194e6 ┆ 749120.0 │
│ 2025-04-08 ┆ 1.829856e6 ┆ 746800.0 │
│ 2025-04-09 ┆ 2.186967e6 ┆ 760962.0 │
│ 2025-04-10 ┆ 1.8566e6   ┆ 740517.0 │
│ 2025-04-11 ┆ 1.229829e6 ┆ 466974.0 │
│ 2025-04-14 ┆ 1.00183e6  ┆ 432062.0 │
│ 2025-04-15 ┆ 920261.0   ┆ 410728.0 │
│ 2025-04-16 ┆ 1.208403e6 ┆ 522101.0 │
│ 2025-04-17 ┆ 1.030903e6 ┆ 480286.0 │
│ 2025-04-21 ┆ 994740.0   ┆ 378270.0 │
│ 2025-04-22 ┆ 1.30105e6  ┆ 492627.0 │
│ 2025-04-23 ┆ 1.445582e6 ┆ 564154.0 │
│ 2025-04-24 ┆ 1.111018e6 ┆ 446511.0 │
│ 2025-04-25 ┆ 1.027888e6 ┆ 433444.0 │
│ 2025-04-28 ┆ 978820.0   ┆ 413972.0 │
│ 2025-04-29 ┆ 984694.0   ┆ 438306.0 │
│ 2025-04-30 ┆ 1.509384e6 ┆ 568585.0 │
│ 2025-05-01 ┆ 1.110529e6 ┆ 456559.0 │
│ 2025-05-02 ┆ 1.057271e6 ┆ 368892.0 │
│ 2025-05-05 ┆ 807865.0   ┆ 302551.0 │
│ 2025-05-06 ┆ 1.077219e6 ┆ 396176.0 │
│ 2025-05-07 ┆ 1.140347e6 ┆ 459671.0 │
│ 2025-05-08 ┆ 1.129065e6 ┆ 428780.0 │
│ 2025-05-09 ┆ 818434.0   ┆ 342202.0 │
│ 2025-05-12 ┆ 1.259819e6 ┆ 430920.0 │
│ 2025-05-13 ┆ 1.068914e6 ┆ 401778.0 │
│ 2025-05-14 ┆ 969011.0   ┆ 380726.0 │
│ 2025-05-15 ┆ 1.044264e6 ┆ 420691.0 │
│ 2025-05-16 ┆ 927514.0   ┆ 309030.0 │
│ 2025-05-19 ┆ 965236.0   ┆ 358457.0 │
│ 2025-05-20 ┆ 918439.0   ┆ 333232.0 │
│ 2025-05-21 ┆ 1.299084e6 ┆ 495944.0 │
│ 2025-05-22 ┆ 1.127484e6 ┆ 384718.0 │
│ 2025-05-23 ┆ 1.126552e6 ┆ 352076.0 │
│ 2025-05-27 ┆ 927444.0   ┆ 331338.0 │
│ 2025-05-28 ┆ 1.001422e6 ┆ 335072.0 │
│ 2025-05-29 ┆ 1.049555e6 ┆ 386227.0 │
│ 2025-05-30 ┆ 1.349986e6 ┆ 430516.0 │
│ 2025-06-02 ┆ 971850.0   ┆ 332526.0 │
│ 2025-06-03 ┆ 949312.0   ┆ 331274.0 │
│ 2025-06-04 ┆ 894093.0   ┆ 308223.0 │
│ 2025-06-05 ┆ 1.332379e6 ┆ 481792.0 │
│ 2025-06-06 ┆ 1.021444e6 ┆ 347619.0 │
│ 2025-06-09 ┆ 720229.0   ┆ 277803.0 │
│ 2025-06-10 ┆ 838725.0   ┆ 332166.0 │
│ 2025-06-11 ┆ 1.221546e6 ┆ 406283.0 │
│ 2025-06-12 ┆ 924053.0   ┆ 292506.0 │
│ 2025-06-13 ┆ 1.068162e6 ┆ 353507.0 │
│ 2025-06-16 ┆ 425665.0   ┆ 126934.0 │
│ 2025-06-17 ┆ 965828.0   ┆ 308204.0 │
│ 2025-06-18 ┆ 965184.0   ┆ 357964.0 │
│ 2025-06-20 ┆ 1.091034e6 ┆ 405185.0 │
│ 2025-06-23 ┆ 1.103344e6 ┆ 429130.0 │
│ 2025-06-24 ┆ 769925.0   ┆ 311282.0 │
│ 2025-06-25 ┆ 748592.0   ┆ 321653.0 │
│ 2025-06-26 ┆ 843090.0   ┆ 325258.0 │
│ 2025-06-27 ┆ 1.129568e6 ┆ 391948.0 │
│ 2025-06-30 ┆ 1.094407e6 ┆ 340245.0 │
│ 2025-07-01 ┆ 1.110064e6 ┆ 405533.0 │
│ 2025-07-02 ┆ 826769.0   ┆ 310488.0 │
│ 2025-07-03 ┆ 539274.0   ┆ 194248.0 │
│ 2025-07-07 ┆ 1.055574e6 ┆ 377682.0 │
│ 2025-07-08 ┆ 914471.0   ┆ 346811.0 │
│ 2025-07-09 ┆ 980133.0   ┆ 382730.0 │
│ 2025-07-10 ┆ 769119.0   ┆ 318905.0 │
│ 2025-07-11 ┆ 831613.0   ┆ 350149.0 │
│ 2025-07-14 ┆ 744986.0   ┆ 320527.0 │
│ 2025-07-15 ┆ 1.020093e6 ┆ 402023.0 │
│ 2025-07-16 ┆ 1.256071e6 ┆ 452197.0 │

In [32]:
ib_volume.describe()

shape: (9, 4)
┌────────────┬────────────────────────────┬───────────────┬───────────────┐
│ statistic  ┆ date                       ┆ ES            ┆ NQ            │
│ ---        ┆ ---                        ┆ ---           ┆ ---           │
│ str        ┆ str                        ┆ f64           ┆ f64           │
╞════════════╪════════════════════════════╪═══════════════╪═══════════════╡
│ count      ┆ 748                        ┆ 748.0         ┆ 748.0         │
│ null_count ┆ 0                          ┆ 0.0           ┆ 0.0           │
│ mean       ┆ 2025-01-01 04:42:59.679144 ┆ 827250.854278 ┆ 302676.066845 │
│ std        ┆ null                       ┆ 642121.965627 ┆ 226561.688618 │
│ min        ┆ 2023-07-05                 ┆ 0.0           ┆ 0.0           │
│ 25%        ┆ 2024-04-05                 ┆ 416.0         ┆ 309.0         │
│ 50%        ┆ 2025-01-02                 ┆ 973076.0      ┆ 374804.0      │
│ 75%        ┆ 2025-10-01                 ┆ 1.262796e6    ┆ 457910.0      │
│ max        ┆ 2026-07-01                 ┆ 2.787467e6    ┆ 909998.0      │
└────────────┴────────────────────────────┴───────────────┴───────────────┘

In [36]:
from datetime import date

df_2y = ib_volume.filter(
    pl.col('date') > date(2024,1,1)
)
df_2y

shape: (623, 3)
┌────────────┬────────────┬──────────┐
│ date       ┆ ES         ┆ NQ       │
│ ---        ┆ ---        ┆ ---      │
│ date       ┆ f64        ┆ f64      │
╞════════════╪════════════╪══════════╡
│ 2024-01-02 ┆ 2.0        ┆ 0.0      │
│ 2024-01-03 ┆ 3.0        ┆ 0.0      │
│ 2024-01-08 ┆ 3.0        ┆ 2.0      │
│ 2024-01-09 ┆ 1.0        ┆ 1.0      │
│ 2024-01-11 ┆ 19.0       ┆ 2.0      │
│ 2024-01-12 ┆ 4.0        ┆ 2.0      │
│ 2024-01-16 ┆ 23.0       ┆ 0.0      │
│ 2024-01-17 ┆ 2.0        ┆ 4.0      │
│ 2024-01-18 ┆ 114.0      ┆ 3.0      │
│ 2024-01-19 ┆ 333.0      ┆ 9.0      │
│ 2024-01-22 ┆ 23.0       ┆ 0.0      │
│ 2024-01-23 ┆ 19.0       ┆ 0.0      │
│ 2024-01-24 ┆ 25.0       ┆ 1.0      │
│ 2024-01-25 ┆ 142.0      ┆ 3.0      │
│ 2024-01-26 ┆ 17.0       ┆ 17.0     │
│ 2024-01-29 ┆ 88.0       ┆ 2.0      │
│ 2024-01-30 ┆ 13.0       ┆ 4.0      │
│ 2024-01-31 ┆ 39.0       ┆ 4.0      │
│ 2024-02-01 ┆ 24.0       ┆ 3.0      │
│ 2024-02-02 ┆ 53.0       ┆ 14.0     │
│ 2024-02-05 ┆ 68.0       ┆ 2.0      │
│ 2024-02-06 ┆ 20.0       ┆ 1.0      │
│ 2024-02-07 ┆ 15.0       ┆ 5.0      │
│ 2024-02-08 ┆ 4.0        ┆ 0.0      │
│ 2024-02-09 ┆ 31.0       ┆ 2.0      │
│ 2024-02-12 ┆ 24.0       ┆ 6.0      │
│ 2024-02-13 ┆ 17.0       ┆ 12.0     │
│ 2024-02-14 ┆ 57.0       ┆ 7.0      │
│ 2024-02-15 ┆ 40.0       ┆ 8.0      │
│ 2024-02-16 ┆ 51.0       ┆ 2.0      │
│ 2024-02-20 ┆ 19.0       ┆ 8.0      │
│ 2024-02-21 ┆ 20.0       ┆ 5.0      │
│ 2024-02-22 ┆ 74.0       ┆ 10.0     │
│ 2024-02-23 ┆ 62.0       ┆ 6.0      │
│ 2024-02-26 ┆ 23.0       ┆ 12.0     │
│ 2024-02-27 ┆ 16.0       ┆ 4.0      │
│ 2024-02-28 ┆ 19.0       ┆ 14.0     │
│ 2024-02-29 ┆ 50.0       ┆ 15.0     │
│ 2024-03-01 ┆ 122.0      ┆ 22.0     │
│ 2024-03-04 ┆ 77.0       ┆ 39.0     │
│ 2024-03-05 ┆ 55.0       ┆ 59.0     │
│ 2024-03-06 ┆ 79.0       ┆ 18.0     │
│ 2024-03-07 ┆ 152.0      ┆ 58.0     │
│ 2024-03-08 ┆ 134.0      ┆ 54.0     │
│ 2024-03-11 ┆ 123.0      ┆ 46.0     │
│ 2024-03-12 ┆ 290.0      ┆ 278.0    │
│ 2024-03-13 ┆ 1294.0     ┆ 48.0     │
│ 2024-03-14 ┆ 416.0      ┆ 145.0    │
│ 2024-03-15 ┆ 756.0      ┆ 516.0    │
│ 2024-03-18 ┆ 472.0      ┆ 349.0    │
│ 2024-03-19 ┆ 399.0      ┆ 459.0    │
│ 2024-03-20 ┆ 1010.0     ┆ 615.0    │
│ 2024-03-21 ┆ 370.0      ┆ 384.0    │
│ 2024-03-22 ┆ 274.0      ┆ 113.0    │
│ 2024-03-25 ┆ 232.0      ┆ 159.0    │
│ 2024-03-26 ┆ 258.0      ┆ 119.0    │
│ 2024-03-27 ┆ 459.0      ┆ 298.0    │
│ 2024-03-28 ┆ 375.0      ┆ 241.0    │
│ 2024-04-01 ┆ 386.0      ┆ 154.0    │
│ 2024-04-02 ┆ 413.0      ┆ 171.0    │
│ 2024-04-03 ┆ 419.0      ┆ 281.0    │
│ 2024-04-04 ┆ 698.0      ┆ 552.0    │
│ 2024-04-05 ┆ 683.0      ┆ 364.0    │
│ 2024-04-08 ┆ 253.0      ┆ 155.0    │
│ 2024-04-09 ┆ 540.0      ┆ 307.0    │
│ 2024-04-10 ┆ 825.0      ┆ 546.0    │
│ 2024-04-11 ┆ 710.0      ┆ 463.0    │
│ 2024-04-12 ┆ 889.0      ┆ 442.0    │
│ 2024-04-15 ┆ 891.0      ┆ 797.0    │
│ 2024-04-16 ┆ 787.0      ┆ 623.0    │
│ 2024-04-17 ┆ 1309.0     ┆ 640.0    │
│ 2024-04-18 ┆ 1008.0     ┆ 680.0    │
│ 2024-04-19 ┆ 881.0      ┆ 846.0    │
│ 2024-04-22 ┆ 556.0      ┆ 555.0    │
│ 2024-04-23 ┆ 519.0      ┆ 438.0    │
│ 2024-04-24 ┆ 533.0      ┆ 309.0    │
│ 2024-04-25 ┆ 688.0      ┆ 486.0    │
│ 2024-04-26 ┆ 642.0      ┆ 407.0    │
│ 2024-04-29 ┆ 242.0      ┆ 163.0    │
│ 2024-04-30 ┆ 448.0      ┆ 406.0    │
│ 2024-05-01 ┆ 1002.0     ┆ 785.0    │
│ 2024-05-02 ┆ 622.0      ┆ 532.0    │
│ 2024-05-03 ┆ 903.0      ┆ 627.0    │
│ 2024-05-06 ┆ 390.0      ┆ 411.0    │
│ 2024-05-07 ┆ 388.0      ┆ 341.0    │
│ 2024-05-08 ┆ 295.0      ┆ 245.0    │
│ 2024-05-09 ┆ 427.0      ┆ 246.0    │
│ 2024-05-10 ┆ 568.0      ┆ 413.0    │
│ 2024-05-13 ┆ 225.0      ┆ 535.0    │
│ 2024-05-14 ┆ 862.0      ┆ 610.0    │
│ 2024-05-15 ┆ 1514.0     ┆ 760.0    │
│ 2024-05-16 ┆ 779.0      ┆ 359.0    │
│ 2024-05-17 ┆ 323.0      ┆ 280.0    │
│ 2024-05-20 ┆ 401.0      ┆ 452.0    │
│ 2024-05-21 ┆ 424.0      ┆ 422.0    │
│ 2024-05-22 ┆ 1091.0     ┆ 675.0    │
│ 2024-05-23 ┆ 1817.0     ┆ 1143.0   │
│ 2024-05-24 ┆ 1200.0     ┆ 601.0    │
│ 2024-05-28 ┆ 1117.0     ┆ 583.0    │
│ 2024-05-29 ┆ 1079.0     ┆ 993.0    │
│ 2024-05-30 ┆ 2483.0     ┆ 947.0    │
│ 2024-05-31 ┆ 3564.0     ┆ 1645.0   │
│ 2024-06-03 ┆ 3139.0     ┆ 1334.0   │
│ 2024-06-04 ┆ 7723.0     ┆ 1922.0   │
│ 2024-06-05 ┆ 7783.0     ┆ 2499.0   │
│ 2024-06-06 ┆ 5694.0     ┆ 1703.0   │
│ 2024-06-07 ┆ 10210.0    ┆ 3593.0   │
│ 2024-06-10 ┆ 7219.0     ┆ 2628.0   │
│ 2024-06-11 ┆ 13276.0    ┆ 4397.0   │
│ 2024-06-12 ┆ 38212.0    ┆ 12385.0  │
│ 2024-06-13 ┆ 162624.0   ┆ 55714.0  │
│ 2024-06-14 ┆ 314706.0   ┆ 136403.0 │
│ 2024-06-17 ┆ 911847.0   ┆ 439542.0 │
│ 2024-06-18 ┆ 826651.0   ┆ 401024.0 │
│ 2024-06-20 ┆ 1.25167e6  ┆ 676527.0 │
│ 2024-06-21 ┆ 1.042563e6 ┆ 458014.0 │
│ 2024-06-24 ┆ 1.172557e6 ┆ 570927.0 │
│ 2024-06-25 ┆ 901562.0   ┆ 464066.0 │
│ 2024-06-26 ┆ 928999.0   ┆ 469909.0 │
│ 2024-06-27 ┆ 1.016008e6 ┆ 489116.0 │
│ 2024-06-28 ┆ 1.497621e6 ┆ 626879.0 │
│ 2024-07-01 ┆ 1.153785e6 ┆ 516718.0 │
│ 2024-07-02 ┆ 1.043401e6 ┆ 503305.0 │
│ 2024-07-03 ┆ 580493.0   ┆ 305547.0 │
│ 2024-07-05 ┆ 884456.0   ┆ 450622.0 │
│ 2024-07-08 ┆ 781998.0   ┆ 417753.0 │
│ 2024-07-09 ┆ 880100.0   ┆ 475745.0 │
│ 2024-07-10 ┆ 994486.0   ┆ 496841.0 │
│ 2024-07-11 ┆ 1.647027e6 ┆ 764887.0 │
│ 2024-07-12 ┆ 1.403663e6 ┆ 594617.0 │
│ 2024-07-15 ┆ 1.471477e6 ┆ 604003.0 │
│ 2024-07-16 ┆ 1.262672e6 ┆ 532302.0 │
│ 2024-07-17 ┆ 1.705285e6 ┆ 672653.0 │
│ 2024-07-18 ┆ 2.210024e6 ┆ 803795.0 │
│ 2024-07-19 ┆ 1.736154e6 ┆ 615341.0 │
│ 2024-07-22 ┆ 1.390992e6 ┆ 511892.0 │
│ 2024-07-23 ┆ 1.164456e6 ┆ 485812.0 │
│ 2024-07-24 ┆ 1.800177e6 ┆ 661714.0 │
│ 2024-07-25 ┆ 2.357403e6 ┆ 763298.0 │
│ 2024-07-26 ┆ 1.671687e6 ┆ 568579.0 │
│ 2024-07-29 ┆ 1.453176e6 ┆ 483022.0 │
│ 2024-07-30 ┆ 1.828945e6 ┆ 644944.0 │
│ 2024-07-31 ┆ 1.723161e6 ┆ 580690.0 │
│ 2024-08-01 ┆ 2.369701e6 ┆ 736265.0 │
│ 2024-08-02 ┆ 2.576469e6 ┆ 616905.0 │
│ 2024-08-05 ┆ 2.313948e6 ┆ 599809.0 │
│ 2024-08-06 ┆ 1.682901e6 ┆ 522515.0 │
│ 2024-08-07 ┆ 1.810284e6 ┆ 572603.0 │
│ 2024-08-08 ┆ 1.448033e6 ┆ 494266.0 │
│ 2024-08-09 ┆ 1.104669e6 ┆ 371635.0 │
│ 2024-08-12 ┆ 1.040041e6 ┆ 392161.0 │
│ 2024-08-13 ┆ 995830.0   ┆ 378468.0 │
│ 2024-08-14 ┆ 1.033172e6 ┆ 435211.0 │
│ 2024-08-15 ┆ 1.091257e6 ┆ 400781.0 │
│ 2024-08-16 ┆ 810910.0   ┆ 336277.0 │
│ 2024-08-19 ┆ 788094.0   ┆ 346846.0 │
│ 2024-08-20 ┆ 852228.0   ┆ 401311.0 │
│ 2024-08-21 ┆ 915179.0   ┆ 409042.0 │
│ 2024-08-22 ┆ 1.228777e6 ┆ 551371.0 │
│ 2024-08-23 ┆ 1.230698e6 ┆ 507254.0 │
│ 2024-08-26 ┆ 941294.0   ┆ 394409.0 │
│ 2024-08-27 ┆ 822964.0   ┆ 349815.0 │
│ 2024-08-28 ┆ 1.192928e6 ┆ 460001.0 │
│ 2024-08-29 ┆ 1.294367e6 ┆ 520493.0 │
│ 2024-08-30 ┆ 1.307103e6 ┆ 405296.0 │
│ 2024-09-03 ┆ 1.508785e6 ┆ 504279.0 │
│ 2024-09-04 ┆ 1.400451e6 ┆ 443141.0 │
│ 2024-09-05 ┆ 1.435434e6 ┆ 457910.0 │
│ 2024-09-06 ┆ 1.877364e6 ┆ 560055.0 │
│ 2024-09-09 ┆ 1.272609e6 ┆ 415869.0 │
│ 2024-09-10 ┆ 1.237367e6 ┆ 426980.0 │
│ 2024-09-11 ┆ 1.858245e6 ┆ 579602.0 │
│ 2024-09-12 ┆ 1.296528e6 ┆ 448670.0 │
│ 2024-09-13 ┆ 911767.0   ┆ 350875.0 │
│ 2024-09-16 ┆ 384438.0   ┆ 182037.0 │
│ 2024-09-17 ┆ 994101.0   ┆ 342243.0 │
│ 2024-09-18 ┆ 1.336663e6 ┆ 444966.0 │
│ 2024-09-19 ┆ 1.201026e6 ┆ 418148.0 │
│ 2024-09-20 ┆ 1.222253e6 ┆ 375943.0 │
│ 2024-09-23 ┆ 849859.0   ┆ 298718.0 │
│ 2024-09-24 ┆ 949145.0   ┆ 361070.0 │
│ 2024-09-25 ┆ 848693.0   ┆ 326136.0 │
│ 2024-09-26 ┆ 1.060948e6 ┆ 392422.0 │
│ 2024-09-27 ┆ 989526.0   ┆ 329755.0 │
│ 2024-09-30 ┆ 1.177744e6 ┆ 413095.0 │
│ 2024-10-01 ┆ 1.713821e6 ┆ 571593.0 │
│ 2024-10-02 ┆ 982650.0   ┆ 368623.0 │
│ 2024-10-03 ┆ 1.157919e6 ┆ 420195.0 │
│ 2024-10-04 ┆ 1.126816e6 ┆ 430570.0 │
│ 2024-10-07 ┆ 939444.0   ┆ 343770.0 │
│ 2024-10-08 ┆ 853947.0   ┆ 332850.0 │
│ 2024-10-09 ┆ 924305.0   ┆ 340185.0 │
│ 2024-10-10 ┆ 849766.0   ┆ 351431.0 │
│ 2024-10-11 ┆ 831774.0   ┆ 306211.0 │
│ 2024-10-14 ┆ 730147.0   ┆ 316467.0 │
│ 2024-10-15 ┆ 1.141292e6 ┆ 442272.0 │
│ 2024-10-16 ┆ 758617.0   ┆ 336934.0 │
│ 2024-10-17 ┆ 970596.0   ┆ 415898.0 │
│ 2024-10-18 ┆ 730385.0   ┆ 298741.0 │
│ 2024-10-21 ┆ 900472.0   ┆ 368435.0 │
│ 2024-10-22 ┆ 824014.0   ┆ 363847.0 │
│ 2024-10-23 ┆ 1.270217e6 ┆ 527838.0 │
│ 2024-10-24 ┆ 967719.0   ┆ 369628.0 │
│ 2024-10-25 ┆ 1.166199e6 ┆ 491757.0 │
│ 2024-10-28 ┆ 782339.0   ┆ 325823.0 │
│ 2024-10-29 ┆ 951328.0   ┆ 400829.0 │
│ 2024-10-30 ┆ 1.063978e6 ┆ 407072.0 │
│ 2024-10-31 ┆ 1.594014e6 ┆ 550193.0 │
│ 2024-11-01 ┆ 1.259321e6 ┆ 439610.0 │
│ 2024-11-04 ┆ 1.062278e6 ┆ 394250.0 │
│ 2024-11-05 ┆ 998048.0   ┆ 368942.0 │
│ 2024-11-06 ┆ 1.279628e6 ┆ 417766.0 │
│ 2024-11-07 ┆ 1.004076e6 ┆ 362980.0 │
│ 2024-11-08 ┆ 885614.0   ┆ 303904.0 │
│ 2024-11-11 ┆ 848998.0   ┆ 364939.0 │
│ 2024-11-12 ┆ 1.123146e6 ┆ 398904.0 │
│ 2024-11-13 ┆ 1.125095e6 ┆ 420893.0 │
│ 2024-11-14 ┆ 1.276933e6 ┆ 450098.0 │
│ 2024-11-15 ┆ 1.541557e6 ┆ 544312.0 │
│ 2024-11-18 ┆ 1.027548e6 ┆ 380041.0 │
│ 2024-11-19 ┆ 1.15842e6  ┆ 371061.0 │
│ 2024-11-20 ┆ 1.326865e6 ┆ 499300.0 │
│ 2024-11-21 ┆ 1.476163e6 ┆ 521848.0 │
│ 2024-11-22 ┆ 1.244348e6 ┆ 416783.0 │
│ 2024-11-25 ┆ 1.333989e6 ┆ 438923.0 │
│ 2024-11-26 ┆ 988177.0   ┆ 370746.0 │
│ 2024-11-27 ┆ 922681.0   ┆ 423341.0 │
│ 2024-11-29 ┆ 564144.0   ┆ 206169.0 │
│ 2024-12-02 ┆ 773527.0   ┆ 387594.0 │
│ 2024-12-03 ┆ 786529.0   ┆ 361173.0 │
│ 2024-12-04 ┆ 902562.0   ┆ 364493.0 │
│ 2024-12-05 ┆ 921302.0   ┆ 349153.0 │
│ 2024-12-06 ┆ 915367.0   ┆ 367453.0 │
│ 2024-12-09 ┆ 1.126732e6 ┆ 418137.0 │
│ 2024-12-10 ┆ 1.105302e6 ┆ 461028.0 │
│ 2024-12-11 ┆ 990655.0   ┆ 445739.0 │
│ 2024-12-12 ┆ 1.152801e6 ┆ 401205.0 │
│ 2024-12-13 ┆ 1.027682e6 ┆ 466826.0 │
│ 2024-12-16 ┆ 378263.0   ┆ 241512.0 │
│ 2024-12-17 ┆ 997849.0   ┆ 379533.0 │
│ 2024-12-18 ┆ 2.009987e6 ┆ 565684.0 │
│ 2024-12-19 ┆ 1.716173e6 ┆ 528702.0 │
│ 2024-12-20 ┆ 1.720536e6 ┆ 630078.0 │
│ 2024-12-23 ┆ 1.102408e6 ┆ 388158.0 │
│ 2024-12-24 ┆ 497383.0   ┆ 199454.0 │
│ 2024-12-26 ┆ 724353.0   ┆ 315494.0 │
│ 2024-12-27 ┆ 1.411128e6 ┆ 489320.0 │
│ 2024-12-30 ┆ 1.282058e6 ┆ 403585.0 │
│ 2024-12-31 ┆ 1.142781e6 ┆ 390822.0 │
│ 2025-01-02 ┆ 1.496415e6 ┆ 509606.0 │
│ 2025-01-03 ┆ 1.009229e6 ┆ 394885.0 │
│ 2025-01-06 ┆ 1.207465e6 ┆ 433696.0 │
│ 2025-01-07 ┆ 1.543464e6 ┆ 540572.0 │
│ 2025-01-08 ┆ 1.436052e6 ┆ 473334.0 │
│ 2025-01-10 ┆ 1.696137e6 ┆ 537724.0 │
│ 2025-01-13 ┆ 1.420722e6 ┆ 446493.0 │
│ 2025-01-14 ┆ 1.525051e6 ┆ 522664.0 │
│ 2025-01-15 ┆ 1.256322e6 ┆ 423599.0 │
│ 2025-01-16 ┆ 1.268023e6 ┆ 456218.0 │
│ 2025-01-17 ┆ 1.082378e6 ┆ 444142.0 │
│ 2025-01-21 ┆ 1.111808e6 ┆ 390335.0 │
│ 2025-01-22 ┆ 987097.0   ┆ 400028.0 │
│ 2025-01-23 ┆ 917464.0   ┆ 376022.0 │
│ 2025-01-24 ┆ 1.017586e6 ┆ 390449.0 │
│ 2025-01-27 ┆ 1.688106e6 ┆ 644920.0 │
│ 2025-01-28 ┆ 1.27936e6  ┆ 503276.0 │
│ 2025-01-29 ┆ 1.342474e6 ┆ 523392.0 │
│ 2025-01-30 ┆ 1.370253e6 ┆ 502110.0 │
│ 2025-01-31 ┆ 1.609577e6 ┆ 545134.0 │
│ 2025-02-03 ┆ 1.710269e6 ┆ 529402.0 │
│ 2025-02-04 ┆ 1.012513e6 ┆ 375872.0 │
│ 2025-02-05 ┆ 956301.0   ┆ 377548.0 │
│ 2025-02-06 ┆ 962902.0   ┆ 351797.0 │
│ 2025-02-07 ┆ 1.463511e6 ┆ 510061.0 │
│ 2025-02-10 ┆ 799826.0   ┆ 294062.0 │
│ 2025-02-11 ┆ 832687.0   ┆ 329733.0 │
│ 2025-02-12 ┆ 1.208683e6 ┆ 410403.0 │
│ 2025-02-13 ┆ 1.250351e6 ┆ 418596.0 │
│ 2025-02-14 ┆ 800631.0   ┆ 341251.0 │
│ 2025-02-18 ┆ 923879.0   ┆ 374804.0 │
│ 2025-02-19 ┆ 879970.0   ┆ 399925.0 │
│ 2025-02-20 ┆ 1.205593e6 ┆ 476740.0 │
│ 2025-02-21 ┆ 1.691282e6 ┆ 614803.0 │
│ 2025-02-24 ┆ 1.504553e6 ┆ 551277.0 │
│ 2025-02-25 ┆ 1.864021e6 ┆ 646535.0 │
│ 2025-02-26 ┆ 1.644114e6 ┆ 545198.0 │
│ 2025-02-27 ┆ 2.198039e6 ┆ 694457.0 │
│ 2025-02-28 ┆ 2.339831e6 ┆ 683202.0 │
│ 2025-03-03 ┆ 2.229904e6 ┆ 685573.0 │
│ 2025-03-04 ┆ 2.787467e6 ┆ 742066.0 │
│ 2025-03-05 ┆ 1.81803e6  ┆ 619208.0 │
│ 2025-03-06 ┆ 2.155366e6 ┆ 613987.0 │
│ 2025-03-07 ┆ 1.865646e6 ┆ 615413.0 │
│ 2025-03-10 ┆ 2.068527e6 ┆ 621572.0 │
│ 2025-03-11 ┆ 2.072069e6 ┆ 642756.0 │
│ 2025-03-12 ┆ 1.513476e6 ┆ 539929.0 │
│ 2025-03-13 ┆ 1.561729e6 ┆ 561496.0 │
│ 2025-03-14 ┆ 1.30764e6  ┆ 535514.0 │
│ 2025-03-17 ┆ 554842.0   ┆ 306099.0 │
│ 2025-03-18 ┆ 1.012705e6 ┆ 177296.0 │
│ 2025-03-19 ┆ 1.161071e6 ┆ 419894.0 │
│ 2025-03-20 ┆ 1.262796e6 ┆ 444527.0 │
│ 2025-03-21 ┆ 1.214828e6 ┆ 468697.0 │
│ 2025-03-24 ┆ 1.106689e6 ┆ 409313.0 │
│ 2025-03-25 ┆ 842430.0   ┆ 369721.0 │
│ 2025-03-26 ┆ 1.269497e6 ┆ 533050.0 │
│ 2025-03-27 ┆ 1.287285e6 ┆ 495099.0 │
│ 2025-03-28 ┆ 1.595221e6 ┆ 564524.0 │
│ 2025-03-31 ┆ 1.766518e6 ┆ 641559.0 │
│ 2025-04-01 ┆ 1.521047e6 ┆ 634848.0 │
│ 2025-04-02 ┆ 1.731713e6 ┆ 696313.0 │
│ 2025-04-03 ┆ 1.823498e6 ┆ 642714.0 │
│ 2025-04-04 ┆ 2.588168e6 ┆ 900886.0 │
│ 2025-04-07 ┆ 2.426194e6 ┆ 749120.0 │
│ 2025-04-08 ┆ 1.829856e6 ┆ 746800.0 │
│ 2025-04-09 ┆ 2.186967e6 ┆ 760962.0 │
│ 2025-04-10 ┆ 1.8566e6   ┆ 740517.0 │
│ 2025-04-11 ┆ 1.229829e6 ┆ 466974.0 │
│ 2025-04-14 ┆ 1.00183e6  ┆ 432062.0 │
│ 2025-04-15 ┆ 920261.0   ┆ 410728.0 │
│ 2025-04-16 ┆ 1.208403e6 ┆ 522101.0 │
│ 2025-04-17 ┆ 1.030903e6 ┆ 480286.0 │
│ 2025-04-21 ┆ 994740.0   ┆ 378270.0 │
│ 2025-04-22 ┆ 1.30105e6  ┆ 492627.0 │
│ 2025-04-23 ┆ 1.445582e6 ┆ 564154.0 │
│ 2025-04-24 ┆ 1.111018e6 ┆ 446511.0 │
│ 2025-04-25 ┆ 1.027888e6 ┆ 433444.0 │
│ 2025-04-28 ┆ 978820.0   ┆ 413972.0 │
│ 2025-04-29 ┆ 984694.0   ┆ 438306.0 │
│ 2025-04-30 ┆ 1.509384e6 ┆ 568585.0 │
│ 2025-05-01 ┆ 1.110529e6 ┆ 456559.0 │
│ 2025-05-02 ┆ 1.057271e6 ┆ 368892.0 │
│ 2025-05-05 ┆ 807865.0   ┆ 302551.0 │
│ 2025-05-06 ┆ 1.077219e6 ┆ 396176.0 │
│ 2025-05-07 ┆ 1.140347e6 ┆ 459671.0 │
│ 2025-05-08 ┆ 1.129065e6 ┆ 428780.0 │
│ 2025-05-09 ┆ 818434.0   ┆ 342202.0 │
│ 2025-05-12 ┆ 1.259819e6 ┆ 430920.0 │
│ 2025-05-13 ┆ 1.068914e6 ┆ 401778.0 │
│ 2025-05-14 ┆ 969011.0   ┆ 380726.0 │
│ 2025-05-15 ┆ 1.044264e6 ┆ 420691.0 │
│ 2025-05-16 ┆ 927514.0   ┆ 309030.0 │
│ 2025-05-19 ┆ 965236.0   ┆ 358457.0 │
│ 2025-05-20 ┆ 918439.0   ┆ 333232.0 │
│ 2025-05-21 ┆ 1.299084e6 ┆ 495944.0 │
│ 2025-05-22 ┆ 1.127484e6 ┆ 384718.0 │
│ 2025-05-23 ┆ 1.126552e6 ┆ 352076.0 │
│ 2025-05-27 ┆ 927444.0   ┆ 331338.0 │
│ 2025-05-28 ┆ 1.001422e6 ┆ 335072.0 │
│ 2025-05-29 ┆ 1.049555e6 ┆ 386227.0 │
│ 2025-05-30 ┆ 1.349986e6 ┆ 430516.0 │
│ 2025-06-02 ┆ 971850.0   ┆ 332526.0 │
│ 2025-06-03 ┆ 949312.0   ┆ 331274.0 │
│ 2025-06-04 ┆ 894093.0   ┆ 308223.0 │
│ 2025-06-05 ┆ 1.332379e6 ┆ 481792.0 │
│ 2025-06-06 ┆ 1.021444e6 ┆ 347619.0 │
│ 2025-06-09 ┆ 720229.0   ┆ 277803.0 │
│ 2025-06-10 ┆ 838725.0   ┆ 332166.0 │
│ 2025-06-11 ┆ 1.221546e6 ┆ 406283.0 │
│ 2025-06-12 ┆ 924053.0   ┆ 292506.0 │
│ 2025-06-13 ┆ 1.068162e6 ┆ 353507.0 │
│ 2025-06-16 ┆ 425665.0   ┆ 126934.0 │
│ 2025-06-17 ┆ 965828.0   ┆ 308204.0 │
│ 2025-06-18 ┆ 965184.0   ┆ 357964.0 │
│ 2025-06-20 ┆ 1.091034e6 ┆ 405185.0 │
│ 2025-06-23 ┆ 1.103344e6 ┆ 429130.0 │
│ 2025-06-24 ┆ 769925.0   ┆ 311282.0 │
│ 2025-06-25 ┆ 748592.0   ┆ 321653.0 │
│ 2025-06-26 ┆ 843090.0   ┆ 325258.0 │
│ 2025-06-27 ┆ 1.129568e6 ┆ 391948.0 │
│ 2025-06-30 ┆ 1.094407e6 ┆ 340245.0 │
│ 2025-07-01 ┆ 1.110064e6 ┆ 405533.0 │
│ 2025-07-02 ┆ 826769.0   ┆ 310488.0 │
│ 2025-07-03 ┆ 539274.0   ┆ 194248.0 │
│ 2025-07-07 ┆ 1.055574e6 ┆ 377682.0 │
│ 2025-07-08 ┆ 914471.0   ┆ 346811.0 │
│ 2025-07-09 ┆ 980133.0   ┆ 382730.0 │
│ 2025-07-10 ┆ 769119.0   ┆ 318905.0 │
│ 2025-07-11 ┆ 831613.0   ┆ 350149.0 │
│ 2025-07-14 ┆ 744986.0   ┆ 320527.0 │
│ 2025-07-15 ┆ 1.020093e6 ┆ 402023.0 │
│ 2025-07-16 ┆ 1.256071e6 ┆ 452197.0 │
│ 2025-07-17 ┆ 847951.0   ┆ 350389.0 │
│ 2025-07-18 ┆ 837806.0   ┆ 364661.0 │
│ 2025-07-21 ┆ 789612.0   ┆ 326566.0 │
│ 2025-07-22 ┆ 970379.0   ┆ 451167.0 │
│ 2025-07-23 ┆ 995445.0   ┆ 420952.0 │
│ 2025-07-24 ┆ 890998.0   ┆ 356837.0 │
│ 2025-07-25 ┆ 665463.0   ┆ 321231.0 │
│ 2025-07-28 ┆ 771975.0   ┆ 339700.0 │
│ 2025-07-29 ┆ 973076.0   ┆ 462601.0 │
│ 2025-07-30 ┆ 1.128086e6 ┆ 459837.0 │
│ 2025-07-31 ┆ 1.56225e6  ┆ 619878.0 │
│ 2025-08-01 ┆ 1.826354e6 ┆ 595987.0 │
│ 2025-08-04 ┆ 1.020131e6 ┆ 351779.0 │
│ 2025-08-05 ┆ 1.197111e6 ┆ 446906.0 │
│ 2025-08-06 ┆ 1.021524e6 ┆ 417366.0 │
│ 2025-08-07 ┆ 1.223036e6 ┆ 447497.0 │
│ 2025-08-08 ┆ 1.013104e6 ┆ 375355.0 │
│ 2025-08-11 ┆ 914648.0   ┆ 360649.0 │
│ 2025-08-12 ┆ 1.005924e6 ┆ 381185.0 │
│ 2025-08-13 ┆ 931899.0   ┆ 382410.0 │
│ 2025-08-14 ┆ 975954.0   ┆ 406020.0 │
│ 2025-08-15 ┆ 900788.0   ┆ 365872.0 │
│ 2025-08-18 ┆ 718231.0   ┆ 324628.0 │
│ 2025-08-19 ┆ 1.067542e6 ┆ 478289.0 │
│ 2025-08-20 ┆ 1.375046e6 ┆ 593606.0 │
│ 2025-08-21 ┆ 1.01362e6  ┆ 425088.0 │
│ 2025-08-22 ┆ 1.223132e6 ┆ 411021.0 │
│ 2025-08-25 ┆ 774725.0   ┆ 315620.0 │
│ 2025-08-26 ┆ 882807.0   ┆ 344035.0 │
│ 2025-08-27 ┆ 808486.0   ┆ 363981.0 │
│ 2025-08-28 ┆ 957454.0   ┆ 385983.0 │
│ 2025-08-29 ┆ 1.138715e6 ┆ 448188.0 │
│ 2025-09-02 ┆ 1.363042e6 ┆ 506193.0 │
│ 2025-09-03 ┆ 1.205924e6 ┆ 457800.0 │
│ 2025-09-04 ┆ 987273.0   ┆ 392524.0 │
│ 2025-09-05 ┆ 1.433929e6 ┆ 556404.0 │
│ 2025-09-08 ┆ 972388.0   ┆ 376489.0 │
│ 2025-09-09 ┆ 981348.0   ┆ 393611.0 │
│ 2025-09-10 ┆ 1.095511e6 ┆ 419437.0 │
│ 2025-09-11 ┆ 963739.0   ┆ 348270.0 │
│ 2025-09-12 ┆ 824004.0   ┆ 320482.0 │
│ 2025-09-15 ┆ 621251.0   ┆ 179107.0 │
│ 2025-09-16 ┆ 845045.0   ┆ 268208.0 │
│ 2025-09-17 ┆ 1.286799e6 ┆ 490862.0 │
│ 2025-09-18 ┆ 1.092361e6 ┆ 407717.0 │
│ 2025-09-19 ┆ 1.054896e6 ┆ 396362.0 │
│ 2025-09-22 ┆ 881175.0   ┆ 386397.0 │
│ 2025-09-23 ┆ 1.096484e6 ┆ 487796.0 │
│ 2025-09-24 ┆ 1.072814e6 ┆ 450803.0 │
│ 2025-09-25 ┆ 1.440581e6 ┆ 571180.0 │
│ 2025-09-26 ┆ 1.093048e6 ┆ 429701.0 │
│ 2025-09-29 ┆ 979471.0   ┆ 416494.0 │
│ 2025-09-30 ┆ 1.292254e6 ┆ 430578.0 │
│ 2025-10-01 ┆ 1.018709e6 ┆ 364163.0 │
│ 2025-10-02 ┆ 986357.0   ┆ 373070.0 │
│ 2025-10-03 ┆ 1.188259e6 ┆ 420546.0 │
│ 2025-10-06 ┆ 873923.0   ┆ 323901.0 │
│ 2025-10-07 ┆ 1.235006e6 ┆ 456287.0 │
│ 2025-10-08 ┆ 867723.0   ┆ 363022.0 │
│ 2025-10-09 ┆ 1.181414e6 ┆ 420963.0 │
│ 2025-10-10 ┆ 2.311968e6 ┆ 839313.0 │
│ 2025-10-13 ┆ 1.289922e6 ┆ 451090.0 │
│ 2025-10-14 ┆ 1.691802e6 ┆ 525225.0 │
│ 2025-10-15 ┆ 1.735349e6 ┆ 521616.0 │
│ 2025-10-16 ┆ 1.969689e6 ┆ 622681.0 │
│ 2025-10-17 ┆ 1.497341e6 ┆ 514832.0 │
│ 2025-10-20 ┆ 956230.0   ┆ 330711.0 │
│ 2025-10-21 ┆ 1.103574e6 ┆ 356094.0 │
│ 2025-10-22 ┆ 1.691265e6 ┆ 601850.0 │
│ 2025-10-23 ┆ 1.137746e6 ┆ 413911.0 │
│ 2025-10-24 ┆ 1.00875e6  ┆ 361988.0 │
│ 2025-10-27 ┆ 943320.0   ┆ 330363.0 │
│ 2025-10-28 ┆ 1.004419e6 ┆ 362078.0 │
│ 2025-10-29 ┆ 1.31815e6  ┆ 460297.0 │
│ 2025-10-30 ┆ 1.442334e6 ┆ 496630.0 │
│ 2025-10-31 ┆ 1.491736e6 ┆ 496778.0 │
│ 2025-11-03 ┆ 1.121263e6 ┆ 372222.0 │
│ 2025-11-04 ┆ 1.305661e6 ┆ 497979.0 │
│ 2025-11-05 ┆ 1.110447e6 ┆ 429638.0 │
│ 2025-11-06 ┆ 1.583091e6 ┆ 626233.0 │
│ 2025-11-07 ┆ 1.749551e6 ┆ 590952.0 │
│ 2025-11-10 ┆ 1.293748e6 ┆ 487414.0 │
│ 2025-11-11 ┆ 1.145211e6 ┆ 425212.0 │
│ 2025-11-12 ┆ 1.190502e6 ┆ 506520.0 │
│ 2025-11-13 ┆ 1.785504e6 ┆ 627032.0 │
│ 2025-11-14 ┆ 1.659652e6 ┆ 646843.0 │
│ 2025-11-17 ┆ 1.60385e6  ┆ 589977.0 │
│ 2025-11-18 ┆ 2.126069e6 ┆ 679122.0 │
│ 2025-11-19 ┆ 1.716925e6 ┆ 627692.0 │
│ 2025-11-20 ┆ 2.590974e6 ┆ 824955.0 │
│ 2025-11-21 ┆ 2.032762e6 ┆ 646255.0 │
│ 2025-11-24 ┆ 1.325236e6 ┆ 463210.0 │
│ 2025-11-25 ┆ 1.379219e6 ┆ 500073.0 │
│ 2025-11-26 ┆ 1.203753e6 ┆ 411522.0 │
│ 2025-11-28 ┆ 300011.0   ┆ 135829.0 │
│ 2025-12-01 ┆ 1.179883e6 ┆ 428621.0 │
│ 2025-12-02 ┆ 1.254698e6 ┆ 469058.0 │
│ 2025-12-03 ┆ 1.050119e6 ┆ 376434.0 │
│ 2025-12-04 ┆ 1.137508e6 ┆ 429467.0 │
│ 2025-12-05 ┆ 1.123878e6 ┆ 409201.0 │
│ 2025-12-08 ┆ 1.033763e6 ┆ 399075.0 │
│ 2025-12-09 ┆ 788820.0   ┆ 328595.0 │
│ 2025-12-10 ┆ 1.20044e6  ┆ 467199.0 │
│ 2025-12-11 ┆ 1.274722e6 ┆ 491852.0 │
│ 2025-12-12 ┆ 1.645103e6 ┆ 605930.0 │
│ 2025-12-15 ┆ 879085.0   ┆ 258809.0 │
│ 2025-12-16 ┆ 1.436903e6 ┆ 440321.0 │
│ 2025-12-17 ┆ 1.393225e6 ┆ 533116.0 │
│ 2025-12-18 ┆ 1.719926e6 ┆ 546700.0 │
│ 2025-12-19 ┆ 1.051405e6 ┆ 387176.0 │
│ 2025-12-22 ┆ 812084.0   ┆ 298007.0 │
│ 2025-12-23 ┆ 709597.0   ┆ 273082.0 │
│ 2025-12-24 ┆ 362557.0   ┆ 127555.0 │
│ 2025-12-26 ┆ 530432.0   ┆ 201564.0 │
│ 2025-12-29 ┆ 703559.0   ┆ 271241.0 │
│ 2025-12-30 ┆ 637215.0   ┆ 250134.0 │
│ 2025-12-31 ┆ 821732.0   ┆ 259885.0 │
│ 2026-01-02 ┆ 1.354882e6 ┆ 460479.0 │
│ 2026-01-05 ┆ 1.024251e6 ┆ 364483.0 │
│ 2026-01-06 ┆ 987902.0   ┆ 369132.0 │
│ 2026-01-07 ┆ 1.064918e6 ┆ 400202.0 │
│ 2026-01-08 ┆ 1.091161e6 ┆ 418753.0 │
│ 2026-01-09 ┆ 1.120839e6 ┆ 415672.0 │
│ 2026-01-12 ┆ 773370.0   ┆ 327744.0 │
│ 2026-01-13 ┆ 1.131535e6 ┆ 459409.0 │

In [37]:
df_2y.describe()

shape: (9, 4)
┌────────────┬────────────────────────────┬───────────────┬───────────────┐
│ statistic  ┆ date                       ┆ ES            ┆ NQ            │
│ ---        ┆ ---                        ┆ ---           ┆ ---           │
│ str        ┆ str                        ┆ f64           ┆ f64           │
╞════════════╪════════════════════════════╪═══════════════╪═══════════════╡
│ count      ┆ 623                        ┆ 623.0         ┆ 623.0         │
│ null_count ┆ 0                          ┆ 0.0           ┆ 0.0           │
│ mean       ┆ 2025-04-03 03:00:17.335473 ┆ 993231.780096 ┆ 363405.579454 │
│ std        ┆ null                       ┆ 574508.680474 ┆ 198848.783566 │
│ min        ┆ 2024-01-02                 ┆ 1.0           ┆ 0.0           │
│ 25%        ┆ 2024-08-20                 ┆ 812084.0      ┆ 320482.0      │
│ 50%        ┆ 2025-04-03                 ┆ 1.050119e6    ┆ 401024.0      │
│ 75%        ┆ 2025-11-14                 ┆ 1.325236e6    ┆ 482400.0      │
│ max        ┆ 2026-07-01                 ┆ 2.787467e6    ┆ 909998.0      │
└────────────┴────────────────────────────┴───────────────┴───────────────┘

In [38]:
ib_prices.describe()

shape: (9, 4)
┌────────────┬────────────────────────────┬─────────────┬──────────────┐
│ statistic  ┆ date                       ┆ ES          ┆ NQ           │
│ ---        ┆ ---                        ┆ ---         ┆ ---          │
│ str        ┆ str                        ┆ f64         ┆ f64          │
╞════════════╪════════════════════════════╪═════════════╪══════════════╡
│ count      ┆ 748                        ┆ 748.0       ┆ 748.0        │
│ null_count ┆ 0                          ┆ 0.0         ┆ 0.0          │
│ mean       ┆ 2025-01-01 04:42:59.679144 ┆ 6150.930816 ┆ 22321.527072 │
│ std        ┆ null                       ┆ 746.576363  ┆ 3383.859194  │
│ min        ┆ 2023-07-05                 ┆ 4599.5      ┆ 16048.5      │
│ 25%        ┆ 2024-04-05                 ┆ 5621.0      ┆ 19970.5      │
│ 50%        ┆ 2025-01-02                 ┆ 6178.25     ┆ 22039.75     │
│ 75%        ┆ 2025-10-01                 ┆ 6742.0      ┆ 24883.0      │
│ max        ┆ 2026-07-01                 ┆ 7687.75     ┆ 31015.75     │
└────────────┴────────────────────────────┴─────────────┴──────────────┘

In [39]:
ib_prices

shape: (748, 3)
┌────────────┬─────────┬──────────┐
│ date       ┆ ES      ┆ NQ       │
│ ---        ┆ ---     ┆ ---      │
│ date       ┆ f64     ┆ f64      │
╞════════════╪═════════╪══════════╡
│ 2023-07-05 ┆ 5036.0  ┆ 17564.0  │
│ 2023-07-06 ┆ 4996.25 ┆ 17430.25 │
│ 2023-07-07 ┆ 4982.25 ┆ 17368.25 │
│ 2023-07-10 ┆ 4992.0  ┆ 17353.0  │
│ 2023-07-11 ┆ 5024.25 ┆ 17429.0  │
│ 2023-07-12 ┆ 5062.0  ┆ 17625.0  │
│ 2023-07-13 ┆ 5097.5  ┆ 17916.5  │
│ 2023-07-14 ┆ 5094.25 ┆ 17903.5  │
│ 2023-07-17 ┆ 5111.5  ┆ 18062.25 │
│ 2023-07-18 ┆ 5149.0  ┆ 18209.25 │
│ 2023-07-19 ┆ 5160.0  ┆ 18191.75 │
│ 2023-07-20 ┆ 5126.5  ┆ 17789.25 │
│ 2023-07-21 ┆ 5126.5  ┆ 17731.5  │
│ 2023-07-24 ┆ 5148.0  ┆ 17755.5  │
│ 2023-07-25 ┆ 5162.0  ┆ 17878.5  │
│ 2023-07-26 ┆ 5162.0  ┆ 17820.75 │
│ 2023-07-27 ┆ 5129.75 ┆ 17777.25 │
│ 2023-07-28 ┆ 5177.0  ┆ 18079.75 │
│ 2023-07-31 ┆ 5185.75 ┆ 18104.75 │
│ 2023-08-01 ┆ 5177.0  ┆ 18061.25 │
│ 2023-08-02 ┆ 5105.0  ┆ 17685.75 │
│ 2023-08-03 ┆ 5088.75 ┆ 17649.0  │
│ 2023-08-04 ┆ 5062.0  ┆ 17556.5  │
│ 2023-08-07 ┆ 5101.0  ┆ 17671.75 │
│ 2023-08-08 ┆ 5079.5  ┆ 17526.0  │
│ 2023-08-09 ┆ 5043.5  ┆ 17334.5  │
│ 2023-08-10 ┆ 5043.5  ┆ 17358.5  │
│ 2023-08-11 ┆ 5038.25 ┆ 17243.0  │
│ 2023-08-14 ┆ 5066.25 ┆ 17433.5  │
│ 2023-08-15 ┆ 5009.25 ┆ 17254.0  │
│ 2023-08-16 ┆ 4971.5  ┆ 17074.5  │
│ 2023-08-17 ┆ 4932.75 ┆ 16895.0  │
│ 2023-08-18 ┆ 4929.5  ┆ 16853.5  │
│ 2023-08-21 ┆ 4962.75 ┆ 17120.0  │
│ 2023-08-22 ┆ 4948.75 ┆ 17090.75 │
│ 2023-08-23 ┆ 5000.5  ┆ 17351.75 │
│ 2023-08-24 ┆ 4933.75 ┆ 16987.25 │
│ 2023-08-25 ┆ 4967.25 ┆ 17115.75 │
│ 2023-08-28 ┆ 4997.25 ┆ 17239.75 │
│ 2023-08-29 ┆ 5067.25 ┆ 17595.5  │
│ 2023-08-30 ┆ 5085.5  ┆ 17689.25 │
│ 2023-08-31 ┆ 5077.0  ┆ 17731.5  │
│ 2023-09-01 ┆ 5082.25 ┆ 17706.5  │
│ 2023-09-05 ┆ 5066.5  ┆ 17728.25 │
│ 2023-09-06 ┆ 5031.75 ┆ 17580.25 │
│ 2023-09-07 ┆ 5014.5  ┆ 17452.0  │
│ 2023-09-08 ┆ 5021.0  ┆ 17469.25 │
│ 2023-09-11 ┆ 5052.25 ┆ 17665.25 │
│ 2023-09-12 ┆ 5024.25 ┆ 17480.25 │
│ 2023-09-13 ┆ 5028.5  ┆ 17534.75 │
│ 2023-09-14 ┆ 5069.5  ┆ 17665.25 │
│ 2023-09-15 ┆ 5007.0  ┆ 17358.5  │
│ 2023-09-18 ┆ 5011.25 ┆ 17380.25 │
│ 2023-09-19 ┆ 5002.75 ┆ 17337.75 │
│ 2023-09-20 ┆ 4956.5  ┆ 17094.0  │
│ 2023-09-21 ┆ 4869.25 ┆ 16786.0  │
│ 2023-09-22 ┆ 4857.25 ┆ 16791.5  │
│ 2023-09-25 ┆ 4876.75 ┆ 16863.25 │
│ 2023-09-26 ┆ 4806.75 ┆ 16622.75 │
│ 2023-09-27 ┆ 4805.75 ┆ 16649.0  │
│ 2023-09-28 ┆ 4828.0  ┆ 16780.75 │
│ 2023-09-29 ┆ 4815.0  ┆ 16787.25 │
│ 2023-10-02 ┆ 4814.0  ┆ 16916.75 │
│ 2023-10-03 ┆ 4747.5  ┆ 16620.75 │
│ 2023-10-04 ┆ 4780.75 ┆ 16849.25 │
│ 2023-10-05 ┆ 4772.25 ┆ 16780.75 │
│ 2023-10-06 ┆ 4831.5  ┆ 17072.25 │
│ 2023-10-09 ┆ 4859.5  ┆ 17153.75 │
│ 2023-10-10 ┆ 4884.5  ┆ 17246.25 │
│ 2023-10-11 ┆ 4905.25 ┆ 17365.5  │
│ 2023-10-12 ┆ 4873.5  ┆ 17296.25 │
│ 2023-10-13 ┆ 4847.25 ┆ 17079.75 │
│ 2023-10-16 ┆ 4897.0  ┆ 17264.75 │
│ 2023-10-17 ┆ 4899.75 ┆ 17212.5  │
│ 2023-10-18 ┆ 4832.25 ┆ 16975.0  │
│ 2023-10-19 ┆ 4786.25 ┆ 16827.25 │
│ 2023-10-20 ┆ 4723.75 ┆ 16577.0  │
│ 2023-10-23 ┆ 4716.75 ┆ 16623.25 │
│ 2023-10-24 ┆ 4750.5  ┆ 16769.0  │
│ 2023-10-25 ┆ 4681.5  ┆ 16362.0  │
│ 2023-10-26 ┆ 4620.25 ┆ 16048.5  │
│ 2023-10-27 ┆ 4599.5  ┆ 16120.0  │
│ 2023-10-30 ┆ 4653.75 ┆ 16284.25 │
│ 2023-10-31 ┆ 4684.75 ┆ 16363.75 │
│ 2023-11-01 ┆ 4731.0  ┆ 16641.0  │
│ 2023-11-02 ┆ 4820.0  ┆ 16926.25 │
│ 2023-11-03 ┆ 4862.75 ┆ 17123.25 │
│ 2023-11-06 ┆ 4873.0  ┆ 17181.5  │
│ 2023-11-07 ┆ 4887.0  ┆ 17336.0  │
│ 2023-11-08 ┆ 4890.75 ┆ 17349.25 │
│ 2023-11-09 ┆ 4850.5  ┆ 17206.25 │
│ 2023-11-10 ┆ 4927.0  ┆ 17577.25 │
│ 2023-11-13 ┆ 4921.75 ┆ 17524.0  │
│ 2023-11-14 ┆ 5012.75 ┆ 17893.25 │
│ 2023-11-15 ┆ 5024.0  ┆ 17909.5  │
│ 2023-11-16 ┆ 5027.0  ┆ 17917.0  │
│ 2023-11-17 ┆ 5032.0  ┆ 17941.5  │
│ 2023-11-20 ┆ 5071.25 ┆ 18168.5  │
│ 2023-11-21 ┆ 5059.5  ┆ 18060.75 │
│ 2023-11-22 ┆ 5077.75 ┆ 18126.5  │
│ 2023-11-24 ┆ 5079.75 ┆ 18095.0  │
│ 2023-11-27 ┆ 5071.25 ┆ 18081.25 │
│ 2023-11-28 ┆ 5071.25 ┆ 18123.25 │
│ 2023-11-29 ┆ 5064.5  ┆ 18096.0  │
│ 2023-11-30 ┆ 5084.25 ┆ 18052.5  │
│ 2023-12-01 ┆ 5108.25 ┆ 18094.0  │
│ 2023-12-04 ┆ 5082.25 ┆ 17903.5  │
│ 2023-12-05 ┆ 5080.0  ┆ 17947.0  │
│ 2023-12-06 ┆ 5059.5  ┆ 17845.75 │
│ 2023-12-07 ┆ 5097.0  ┆ 18089.5  │
│ 2023-12-08 ┆ 5121.75 ┆ 18158.0  │
│ 2023-12-11 ┆ 5141.5  ┆ 18321.25 │
│ 2023-12-12 ┆ 5162.5  ┆ 18470.25 │
│ 2023-12-13 ┆ 5227.0  ┆ 18687.5  │
│ 2023-12-14 ┆ 5241.5  ┆ 18659.5  │
│ 2023-12-15 ┆ 5237.25 ┆ 18733.75 │
│ 2023-12-18 ┆ 5264.25 ┆ 18862.0  │
│ 2023-12-19 ┆ 5293.75 ┆ 18950.25 │
│ 2023-12-20 ┆ 5214.5  ┆ 18667.25 │
│ 2023-12-21 ┆ 5265.5  ┆ 18875.0  │
│ 2023-12-22 ┆ 5274.0  ┆ 18899.0  │
│ 2023-12-26 ┆ 5295.75 ┆ 19011.75 │
│ 2023-12-27 ┆ 5305.75 ┆ 19043.75 │
│ 2023-12-28 ┆ 5304.75 ┆ 19016.5  │
│ 2023-12-29 ┆ 5290.25 ┆ 18936.0  │
│ 2024-01-02 ┆ 5255.5  ┆ 18608.5  │
│ 2024-01-03 ┆ 5212.5  ┆ 18408.75 │
│ 2024-01-08 ┆ 5272.75 ┆ 18645.5  │
│ 2024-01-09 ┆ 5259.0  ┆ 18629.25 │
│ 2024-01-11 ┆ 5288.0  ┆ 18784.75 │
│ 2024-01-12 ┆ 5286.75 ┆ 18885.0  │
│ 2024-01-16 ┆ 5269.5  ┆ 18882.75 │
│ 2024-01-17 ┆ 5239.5  ┆ 18777.75 │
│ 2024-01-18 ┆ 5286.25 ┆ 19041.5  │
│ 2024-01-19 ┆ 5351.75 ┆ 19417.5  │
│ 2024-01-22 ┆ 5365.75 ┆ 19441.5  │
│ 2024-01-23 ┆ 5381.25 ┆ 19523.0  │
│ 2024-01-24 ┆ 5385.25 ┆ 19621.0  │
│ 2024-01-25 ┆ 5412.0  ┆ 19635.5  │
│ 2024-01-26 ┆ 5404.75 ┆ 19514.5  │
│ 2024-01-29 ┆ 5446.0  ┆ 19721.25 │
│ 2024-01-30 ┆ 5443.25 ┆ 19594.75 │
│ 2024-01-31 ┆ 5352.25 ┆ 19215.75 │
│ 2024-02-01 ┆ 5415.0  ┆ 19424.25 │
│ 2024-02-02 ┆ 5476.75 ┆ 19752.0  │
│ 2024-02-05 ┆ 5457.5  ┆ 19715.75 │
│ 2024-02-06 ┆ 5470.5  ┆ 19668.25 │
│ 2024-02-07 ┆ 5515.25 ┆ 19867.0  │
│ 2024-02-08 ┆ 5518.75 ┆ 19901.25 │
│ 2024-02-09 ┆ 5548.0  ┆ 20096.0  │
│ 2024-02-12 ┆ 5545.75 ┆ 20015.0  │
│ 2024-02-13 ┆ 5471.0  ┆ 19700.5  │
│ 2024-02-14 ┆ 5522.0  ┆ 19928.25 │
│ 2024-02-15 ┆ 5553.75 ┆ 19970.5  │
│ 2024-02-16 ┆ 5525.25 ┆ 19789.75 │
│ 2024-02-20 ┆ 5493.5  ┆ 19632.5  │
│ 2024-02-21 ┆ 5499.0  ┆ 19556.0  │
│ 2024-02-22 ┆ 5613.25 ┆ 20119.25 │
│ 2024-02-23 ┆ 5617.5  ┆ 20058.75 │
│ 2024-02-26 ┆ 5594.75 ┆ 20045.0  │
│ 2024-02-27 ┆ 5605.25 ┆ 20093.75 │
│ 2024-02-28 ┆ 5595.25 ┆ 19978.0  │
│ 2024-02-29 ┆ 5621.0  ┆ 20168.25 │
│ 2024-03-01 ┆ 5666.5  ┆ 20451.75 │
│ 2024-03-04 ┆ 5659.25 ┆ 20372.5  │
│ 2024-03-05 ┆ 5600.75 ┆ 20005.5  │
│ 2024-03-06 ┆ 5630.0  ┆ 20130.75 │
│ 2024-03-07 ┆ 5685.25 ┆ 20436.5  │
│ 2024-03-08 ┆ 5650.0  ┆ 20142.75 │
│ 2024-03-11 ┆ 5642.75 ┆ 20052.25 │
│ 2024-03-12 ┆ 5704.0  ┆ 20342.75 │
│ 2024-03-13 ┆ 5695.0  ┆ 20182.0  │
│ 2024-03-14 ┆ 5679.0  ┆ 20118.25 │
│ 2024-03-15 ┆ 5641.5  ┆ 19887.75 │
│ 2024-03-18 ┆ 5677.25 ┆ 20079.0  │
│ 2024-03-19 ┆ 5706.0  ┆ 20121.25 │
│ 2024-03-20 ┆ 5754.25 ┆ 20348.5  │
│ 2024-03-21 ┆ 5772.0  ┆ 20442.75 │
│ 2024-03-22 ┆ 5761.25 ┆ 20455.25 │
│ 2024-03-25 ┆ 5745.0  ┆ 20388.5  │
│ 2024-03-26 ┆ 5731.0  ┆ 20318.0  │
│ 2024-03-27 ┆ 5778.0  ┆ 20378.25 │
│ 2024-03-28 ┆ 5779.0  ┆ 20351.25 │
│ 2024-04-01 ┆ 5764.75 ┆ 20374.75 │
│ 2024-04-02 ┆ 5726.75 ┆ 20189.25 │
│ 2024-04-03 ┆ 5733.0  ┆ 20237.0  │
│ 2024-04-04 ┆ 5657.25 ┆ 19911.0  │
│ 2024-04-05 ┆ 5718.75 ┆ 20155.0  │
│ 2024-04-08 ┆ 5719.25 ┆ 20150.0  │
│ 2024-04-09 ┆ 5726.5  ┆ 20220.25 │
│ 2024-04-10 ┆ 5671.0  ┆ 20047.25 │
│ 2024-04-11 ┆ 5709.0  ┆ 20363.25 │
│ 2024-04-12 ┆ 5626.75 ┆ 20027.75 │
│ 2024-04-15 ┆ 5557.5  ┆ 19697.25 │
│ 2024-04-16 ┆ 5545.0  ┆ 19701.25 │
│ 2024-04-17 ┆ 5512.5  ┆ 19458.5  │
│ 2024-04-18 ┆ 5497.75 ┆ 19336.75 │
│ 2024-04-19 ┆ 5448.25 ┆ 18929.75 │
│ 2024-04-22 ┆ 5495.75 ┆ 19115.5  │
│ 2024-04-23 ┆ 5560.25 ┆ 19397.25 │
│ 2024-04-24 ┆ 5561.5  ┆ 19460.5  │
│ 2024-04-25 ┆ 5534.25 ┆ 19355.0  │
│ 2024-04-26 ┆ 5587.75 ┆ 19658.75 │
│ 2024-04-29 ┆ 5604.0  ┆ 19721.25 │
│ 2024-04-30 ┆ 5517.25 ┆ 19357.5  │
│ 2024-05-01 ┆ 5494.5  ┆ 19210.5  │
│ 2024-05-02 ┆ 5543.25 ┆ 19440.5  │
│ 2024-05-03 ┆ 5612.25 ┆ 19826.75 │
│ 2024-05-06 ┆ 5669.0  ┆ 20040.25 │
│ 2024-05-07 ┆ 5677.0  ┆ 20045.75 │
│ 2024-05-08 ┆ 5676.0  ┆ 20032.0  │
│ 2024-05-09 ┆ 5704.75 ┆ 20062.0  │
│ 2024-05-10 ┆ 5712.75 ┆ 20107.25 │
│ 2024-05-13 ┆ 5712.25 ┆ 20153.0  │
│ 2024-05-14 ┆ 5738.5  ┆ 20286.25 │
│ 2024-05-15 ┆ 5808.0  ┆ 20591.0  │
│ 2024-05-16 ┆ 5794.75 ┆ 20546.75 │
│ 2024-05-17 ┆ 5802.25 ┆ 20532.0  │
│ 2024-05-20 ┆ 5807.5  ┆ 20674.25 │
│ 2024-05-21 ┆ 5822.75 ┆ 20715.25 │
│ 2024-05-22 ┆ 5804.0  ┆ 20702.5  │
│ 2024-05-23 ┆ 5757.5  ┆ 20604.5  │
│ 2024-05-24 ┆ 5797.0  ┆ 20801.5  │
│ 2024-05-28 ┆ 5800.25 ┆ 20873.5  │
│ 2024-05-29 ┆ 5756.25 ┆ 20723.0  │
│ 2024-05-30 ┆ 5722.75 ┆ 20507.5  │
│ 2024-05-31 ┆ 5769.0  ┆ 20489.25 │
│ 2024-06-03 ┆ 5771.25 ┆ 20550.0  │
│ 2024-06-04 ┆ 5778.5  ┆ 20612.75 │
│ 2024-06-05 ┆ 5846.25 ┆ 21024.0  │
│ 2024-06-06 ┆ 5844.0  ┆ 21011.25 │
│ 2024-06-07 ┆ 5835.5  ┆ 20987.0  │
│ 2024-06-10 ┆ 5852.5  ┆ 21067.0  │
│ 2024-06-11 ┆ 5866.5  ┆ 21212.75 │
│ 2024-06-12 ┆ 5914.25 ┆ 21495.25 │
│ 2024-06-13 ┆ 5926.0  ┆ 21612.25 │
│ 2024-06-14 ┆ 5924.75 ┆ 21701.25 │
│ 2024-06-17 ┆ 5972.0  ┆ 21970.25 │
│ 2024-06-18 ┆ 5986.5  ┆ 21974.0  │
│ 2024-06-20 ┆ 5970.25 ┆ 21794.75 │
│ 2024-06-21 ┆ 5959.0  ┆ 21741.75 │
│ 2024-06-24 ┆ 5940.5  ┆ 21489.25 │
│ 2024-06-25 ┆ 5962.0  ┆ 21730.25 │
│ 2024-06-26 ┆ 5969.0  ┆ 21774.25 │
│ 2024-06-27 ┆ 5971.75 ┆ 21803.5  │
│ 2024-06-28 ┆ 5945.5  ┆ 21681.5  │
│ 2024-07-01 ┆ 5958.5  ┆ 21817.0  │
│ 2024-07-02 ┆ 5996.25 ┆ 22038.25 │
│ 2024-07-03 ┆ 6019.5  ┆ 22208.25 │
│ 2024-07-05 ┆ 6053.0  ┆ 22436.0  │
│ 2024-07-08 ┆ 6057.0  ┆ 22478.25 │
│ 2024-07-09 ┆ 6063.5  ┆ 22498.75 │
│ 2024-07-10 ┆ 6124.75 ┆ 22739.5  │
│ 2024-07-11 ┆ 6072.75 ┆ 22241.25 │
│ 2024-07-12 ┆ 6099.75 ┆ 22330.75 │
│ 2024-07-15 ┆ 6119.25 ┆ 22395.75 │
│ 2024-07-16 ┆ 6156.25 ┆ 22411.25 │
│ 2024-07-17 ┆ 6072.0  ┆ 21757.75 │
│ 2024-07-18 ┆ 6024.0  ┆ 21651.0  │
│ 2024-07-19 ┆ 5980.0  ┆ 21448.25 │
│ 2024-07-22 ┆ 6041.5  ┆ 21761.5  │
│ 2024-07-23 ┆ 6029.0  ┆ 21679.0  │
│ 2024-07-24 ┆ 5892.0  ┆ 20893.75 │
│ 2024-07-25 ┆ 5859.0  ┆ 20664.0  │
│ 2024-07-26 ┆ 5921.25 ┆ 20862.25 │
│ 2024-07-29 ┆ 5925.5  ┆ 20900.25 │
│ 2024-07-30 ┆ 5892.75 ┆ 20603.25 │
│ 2024-07-31 ┆ 5984.75 ┆ 21222.25 │
│ 2024-08-01 ┆ 5901.0  ┆ 20697.75 │
│ 2024-08-02 ┆ 5788.75 ┆ 20189.75 │
│ 2024-08-05 ┆ 5618.0  ┆ 19599.0  │
│ 2024-08-06 ┆ 5670.5  ┆ 19779.25 │
│ 2024-08-07 ┆ 5628.75 ┆ 19548.0  │
│ 2024-08-08 ┆ 5758.75 ┆ 20156.0  │
│ 2024-08-09 ┆ 5782.5  ┆ 20254.75 │
│ 2024-08-12 ┆ 5782.0  ┆ 20280.25 │
│ 2024-08-13 ┆ 5878.0  ┆ 20786.0  │
│ 2024-08-14 ┆ 5897.5  ┆ 20797.75 │
│ 2024-08-15 ┆ 5995.0  ┆ 21305.0  │
│ 2024-08-16 ┆ 6006.5  ┆ 21331.5  │
│ 2024-08-19 ┆ 6062.25 ┆ 21605.75 │
│ 2024-08-20 ┆ 6051.25 ┆ 21553.25 │
│ 2024-08-21 ┆ 6074.5  ┆ 21662.0  │
│ 2024-08-22 ┆ 6023.5  ┆ 21301.75 │
│ 2024-08-23 ┆ 6086.5  ┆ 21532.75 │
│ 2024-08-26 ┆ 6069.75 ┆ 21315.75 │
│ 2024-08-27 ┆ 6078.0  ┆ 21383.75 │
│ 2024-08-28 ┆ 6041.0  ┆ 21124.75 │
│ 2024-08-29 ┆ 6040.75 ┆ 21100.25 │
│ 2024-08-30 ┆ 6095.5  ┆ 21350.25 │
│ 2024-09-03 ┆ 5967.25 ┆ 20679.5  │
│ 2024-09-04 ┆ 5954.5  ┆ 20631.75 │
│ 2024-09-05 ┆ 5935.5  ┆ 20632.75 │
│ 2024-09-06 ┆ 5835.5  ┆ 20083.0  │
│ 2024-09-09 ┆ 5900.25 ┆ 20337.75 │
│ 2024-09-10 ┆ 5926.5  ┆ 20524.5  │
│ 2024-09-11 ┆ 5988.25 ┆ 20967.25 │
│ 2024-09-12 ┆ 6032.25 ┆ 21159.0  │
│ 2024-09-13 ┆ 6062.0  ┆ 21249.5  │
│ 2024-09-16 ┆ 6070.75 ┆ 21143.5  │
│ 2024-09-17 ┆ 6072.0  ┆ 21155.0  │
│ 2024-09-18 ┆ 6050.25 ┆ 21052.5  │
│ 2024-09-19 ┆ 6154.75 ┆ 21598.25 │
│ 2024-09-20 ┆ 6137.75 ┆ 21534.0  │
│ 2024-09-23 ┆ 6153.5  ┆ 21589.5  │
│ 2024-09-24 ┆ 6169.75 ┆ 21684.0  │
│ 2024-09-25 ┆ 6155.75 ┆ 21710.0  │
│ 2024-09-26 ┆ 6183.0  ┆ 21875.75 │
│ 2024-09-27 ┆ 6168.75 ┆ 21741.75 │
│ 2024-09-30 ┆ 6193.25 ┆ 21784.5  │
│ 2024-10-01 ┆ 6135.25 ┆ 21476.75 │
│ 2024-10-02 ┆ 6135.75 ┆ 21514.0  │
│ 2024-10-03 ┆ 6124.25 ┆ 21493.0  │
│ 2024-10-04 ┆ 6178.25 ┆ 21747.75 │
│ 2024-10-07 ┆ 6119.25 ┆ 21495.75 │
│ 2024-10-08 ┆ 6178.75 ┆ 21824.5  │
│ 2024-10-09 ┆ 6222.0  ┆ 22002.0  │
│ 2024-10-10 ┆ 6209.0  ┆ 21965.5  │
│ 2024-10-11 ┆ 6241.75 ┆ 21987.25 │
│ 2024-10-14 ┆ 6293.5  ┆ 22169.25 │
│ 2024-10-15 ┆ 6245.0  ┆ 21871.25 │
│ 2024-10-16 ┆ 6270.75 ┆ 21879.25 │
│ 2024-10-17 ┆ 6270.75 ┆ 21899.25 │
│ 2024-10-18 ┆ 6291.0  ┆ 22023.5  │
│ 2024-10-21 ┆ 6280.75 ┆ 22062.0  │
│ 2024-10-22 ┆ 6276.75 ┆ 22086.25 │
│ 2024-10-23 ┆ 6218.25 ┆ 21740.5  │
│ 2024-10-24 ┆ 6230.25 ┆ 21912.25 │
│ 2024-10-25 ┆ 6227.25 ┆ 22039.75 │
│ 2024-10-28 ┆ 6243.75 ┆ 22038.0  │
│ 2024-10-29 ┆ 6253.75 ┆ 22252.5  │
│ 2024-10-30 ┆ 6233.5  ┆ 22078.5  │
│ 2024-10-31 ┆ 6112.75 ┆ 21527.0  │
│ 2024-11-01 ┆ 6133.75 ┆ 21668.25 │
│ 2024-11-04 ┆ 6117.75 ┆ 21596.0  │
│ 2024-11-05 ┆ 6191.25 ┆ 21871.0  │
│ 2024-11-06 ┆ 6346.75 ┆ 22464.75 │
│ 2024-11-07 ┆ 6395.25 ┆ 22820.25 │
│ 2024-11-08 ┆ 6418.0  ┆ 22827.25 │
│ 2024-11-11 ┆ 6425.0  ┆ 22812.75 │
│ 2024-11-12 ┆ 6405.0  ┆ 22782.5  │
│ 2024-11-13 ┆ 6408.25 ┆ 22750.25 │
│ 2024-11-14 ┆ 6368.0  ┆ 22591.25 │
│ 2024-11-15 ┆ 6281.0  ┆ 22034.5  │
│ 2024-11-18 ┆ 6306.0  ┆ 22184.75 │
│ 2024-11-19 ┆ 6326.0  ┆ 22329.0  │
│ 2024-11-20 ┆ 6325.0  ┆ 22308.75 │
│ 2024-11-21 ┆ 6359.75 ┆ 22395.5  │
│ 2024-11-22 ┆ 6377.25 ┆ 22417.25 │
│ 2024-11-25 ┆ 6398.0  ┆ 22450.0  │
│ 2024-11-26 ┆ 6432.0  ┆ 22571.75 │
│ 2024-11-27 ┆ 6407.25 ┆ 22377.75 │
│ 2024-11-29 ┆ 6446.0  ┆ 22571.75 │
│ 2024-12-02 ┆ 6457.0  ┆ 22813.0  │
│ 2024-12-03 ┆ 6458.5  ┆ 22881.25 │
│ 2024-12-04 ┆ 6496.0  ┆ 23155.5  │
│ 2024-12-05 ┆ 6485.75 ┆ 23087.5  │
│ 2024-12-06 ┆ 6496.75 ┆ 23284.75 │
│ 2024-12-09 ┆ 6461.25 ┆ 23098.75 │
│ 2024-12-10 ┆ 6440.5  ┆ 23014.5  │
│ 2024-12-11 ┆ 6490.0  ┆ 23431.75 │
│ 2024-12-12 ┆ 6456.0  ┆ 23279.0  │
│ 2024-12-13 ┆ 6450.25 ┆ 23434.25 │
│ 2024-12-16 ┆ 6477.0  ┆ 23772.5  │
│ 2024-12-17 ┆ 6448.75 ┆ 23673.25 │
│ 2024-12-18 ┆ 6252.0  ┆ 22811.0  │
│ 2024-12-19 ┆ 6245.5  ┆ 22680.75 │
│ 2024-12-20 ┆ 6316.75 ┆ 22879.75 │
│ 2024-12-23 ┆ 6352.75 ┆ 23077.75 │
│ 2024-12-24 ┆ 6418.0  ┆ 23369.75 │
│ 2024-12-26 ┆ 6415.0  ┆ 23348.0  │
│ 2024-12-27 ┆ 6343.25 ┆ 23019.75 │
│ 2024-12-30 ┆ 6271.5  ┆ 22720.25 │
│ 2024-12-31 ┆ 6247.25 ┆ 22519.0  │
│ 2025-01-02 ┆ 6227.0  ┆ 22456.5  │
│ 2025-01-03 ┆ 6303.75 ┆ 22826.75 │
│ 2025-01-06 ┆ 6336.5  ┆ 23068.5  │
│ 2025-01-07 ┆ 6266.75 ┆ 22660.25 │
│ 2025-01-08 ┆ 6272.0  ┆ 22661.5  │
│ 2025-01-10 ┆ 6174.0  ┆ 22295.75 │
│ 2025-01-13 ┆ 6182.75 ┆ 22222.75 │
│ 2025-01-14 ┆ 6191.0  ┆ 22193.25 │
│ 2025-01-15 ┆ 6303.25 ┆ 22703.25 │
│ 2025-01-16 ┆ 6289.0  ┆ 22543.75 │
│ 2025-01-17 ┆ 6350.0  ┆ 22909.75 │
│ 2025-01-21 ┆ 6403.5  ┆ 23031.5  │
│ 2025-01-22 ┆ 6441.75 ┆ 23340.0  │
│ 2025-01-23 ┆ 6474.75 ┆ 23380.25 │
│ 2025-01-24 ┆ 6455.0  ┆ 23245.5  │
│ 2025-01-27 ┆ 6364.0  ┆ 22553.0  │
│ 2025-01-28 ┆ 6417.0  ┆ 22895.75 │
│ 2025-01-29 ┆ 6386.0  ┆ 22833.75 │
│ 2025-01-30 ┆ 6419.25 ┆ 22941.5  │
│ 2025-01-31 ┆ 6385.75 ┆ 22903.75 │
│ 2025-02-03 ┆ 6338.25 ┆ 22708.25 │
│ 2025-02-04 ┆ 6381.25 ┆ 22989.75 │
│ 2025-02-05 ┆ 6406.0  ┆ 23088.25 │
│ 2025-02-06 ┆ 6426.5  ┆ 23203.5  │
│ 2025-02-07 ┆ 6367.0  ┆ 22905.5  │
│ 2025-02-10 ┆ 6408.25 ┆ 23176.75 │
│ 2025-02-11 ┆ 6412.0  ┆ 23113.25 │
│ 2025-02-12 ┆ 6391.5  ┆ 23132.5  │
│ 2025-02-13 ┆ 6457.25 ┆ 23459.75 │
│ 2025-02-14 ┆ 6453.75 ┆ 23547.75 │
│ 2025-02-18 ┆ 6469.25 ┆ 23586.0  │
│ 2025-02-19 ┆ 6486.5  ┆ 23605.25 │
│ 2025-02-20 ┆ 6458.5  ┆ 23490.0  │
│ 2025-02-21 ┆ 6345.5  ┆ 22999.25 │
│ 2025-02-24 ┆ 6315.75 ┆ 22724.5  │
│ 2025-02-25 ┆ 6283.25 ┆ 22436.75 │
│ 2025-02-26 ┆ 6284.0  ┆ 22477.0  │
│ 2025-02-27 ┆ 6184.5  ┆ 21860.5  │
│ 2025-02-28 ┆ 6276.25 ┆ 22193.25 │
│ 2025-03-03 ┆ 6168.25 ┆ 21714.5  │
│ 2025-03-04 ┆ 6093.25 ┆ 21641.0  │
│ 2025-03-05 ┆ 6158.25 ┆ 21923.25 │
│ 2025-03-06 ┆ 6047.75 ┆ 21312.5  │
│ 2025-03-07 ┆ 6079.0  ┆ 21461.5  │
│ 2025-03-10 ┆ 5915.75 ┆ 20637.25 │
│ 2025-03-11 ┆ 5869.75 ┆ 20580.25 │
│ 2025-03-12 ┆ 5898.75 ┆ 20813.0  │
│ 2025-03-13 ┆ 5817.5  ┆ 20421.0  │
│ 2025-03-14 ┆ 5936.0  ┆ 20912.25 │
│ 2025-03-17 ┆ 5978.25 ┆ 21039.25 │
│ 2025-03-18 ┆ 5912.75 ┆ 20684.0  │
│ 2025-03-19 ┆ 5975.75 ┆ 20945.5  │
│ 2025-03-20 ┆ 5958.0  ┆ 20870.25 │
│ 2025-03-21 ┆ 5963.75 ┆ 20956.0  │
│ 2025-03-24 ┆ 6065.25 ┆ 21390.0  │
│ 2025-03-25 ┆ 6076.75 ┆ 21510.0  │
│ 2025-03-26 ┆ 6006.75 ┆ 21119.25 │
│ 2025-03-27 ┆ 5985.75 ┆ 20986.75 │
│ 2025-03-28 ┆ 5864.5  ┆ 20427.0  │
│ 2025-03-31 ┆ 5896.0  ┆ 20408.5  │
│ 2025-04-01 ┆ 5918.0  ┆ 20581.75 │
│ 2025-04-02 ┆ 5957.5  ┆ 20743.0  │
│ 2025-04-03 ┆ 5666.0  ┆ 19606.5  │
│ 2025-04-04 ┆ 5329.75 ┆ 18413.25 │
│ 2025-04-07 ┆ 5316.0  ┆ 18438.75 │
│ 2025-04-08 ┆ 5235.75 ┆ 18103.5  │
│ 2025-04-09 ┆ 5726.75 ┆ 20250.25 │
│ 2025-04-10 ┆ 5529.5  ┆ 19406.0  │
│ 2025-04-11 ┆ 5622.75 ┆ 19745.0  │
│ 2025-04-14 ┆ 5674.25 ┆ 19878.75 │
│ 2025-04-15 ┆ 5661.25 ┆ 19905.5  │
│ 2025-04-16 ┆ 5533.5  ┆ 19301.75 │
│ 2025-04-17 ┆ 5540.75 ┆ 19297.0  │
│ 2025-04-21 ┆ 5407.25 ┆ 18815.75 │
│ 2025-04-22 ┆ 5543.0  ┆ 19301.5  │
│ 2025-04-23 ┆ 5633.75 ┆ 19741.5  │
│ 2025-04-24 ┆ 5747.75 ┆ 20285.25 │
│ 2025-04-25 ┆ 5788.0  ┆ 20509.0  │
│ 2025-04-28 ┆ 5791.5  ┆ 20501.5  │
│ 2025-04-29 ┆ 5823.5  ┆ 20621.25 │
│ 2025-04-30 ┆ 5826.75 ┆ 20638.5  │
│ 2025-05-01 ┆ 5864.75 ┆ 20861.25 │
│ 2025-05-02 ┆ 5954.0  ┆ 21202.0  │
│ 2025-05-05 ┆ 5915.25 ┆ 21055.25 │
│ 2025-05-06 ┆ 5867.25 ┆ 20867.25 │
│ 2025-05-07 ┆ 5894.75 ┆ 20956.0  │
│ 2025-05-08 ┆ 5928.5  ┆ 21152.5  │
│ 2025-05-09 ┆ 5921.75 ┆ 21140.5  │
│ 2025-05-12 ┆ 6116.75 ┆ 21993.0  │
│ 2025-05-13 ┆ 6158.0  ┆ 22338.75 │
│ 2025-05-14 ┆ 6162.25 ┆ 22459.0  │
│ 2025-05-15 ┆ 6188.0  ┆ 22467.0  │
│ 2025-05-16 ┆ 6232.0  ┆ 22578.0  │
│ 2025-05-19 ┆ 6239.25 ┆ 22600.25 │
│ 2025-05-20 ┆ 6215.5  ┆ 22516.5  │
│ 2025-05-21 ┆ 6112.75 ┆ 22211.5  │
│ 2025-05-22 ┆ 6108.25 ┆ 22234.0  │
│ 2025-05-23 ┆ 6066.75 ┆ 22020.75 │
│ 2025-05-27 ┆ 6189.0  ┆ 22530.25 │
│ 2025-05-28 ┆ 6156.25 ┆ 22445.5  │
│ 2025-05-29 ┆ 6177.0  ┆ 22475.75 │
│ 2025-05-30 ┆ 6170.0  ┆ 22442.5  │
│ 2025-06-02 ┆ 6202.5  ┆ 22608.0  │
│ 2025-06-03 ┆ 6238.25 ┆ 22788.0  │
│ 2025-06-04 ┆ 6237.75 ┆ 22851.5  │
│ 2025-06-05 ┆ 6201.25 ┆ 22658.25 │
│ 2025-06-06 ┆ 6264.5  ┆ 22875.75 │
│ 2025-06-09 ┆ 6268.25 ┆ 22909.25 │
│ 2025-06-10 ┆ 6304.5  ┆ 23057.25 │
│ 2025-06-11 ┆ 6287.75 ┆ 22978.5  │
│ 2025-06-12 ┆ 6309.25 ┆ 23025.75 │
│ 2025-06-13 ┆ 6236.0  ┆ 22723.25 │
│ 2025-06-16 ┆ 6294.75 ┆ 23035.25 │
│ 2025-06-17 ┆ 6242.0  ┆ 22814.75 │
│ 2025-06-18 ┆ 6237.5  ┆ 22803.5  │
│ 2025-06-20 ┆ 6220.75 ┆ 22699.25 │
│ 2025-06-23 ┆ 6281.75 ┆ 22936.75 │
│ 2025-06-24 ┆ 6353.25 ┆ 23289.5  │
│ 2025-06-25 ┆ 6354.0  ┆ 23339.5  │
│ 2025-06-26 ┆ 6403.75 ┆ 23556.0  │
│ 2025-06-27 ┆ 6433.25 ┆ 23641.5  │
│ 2025-06-30 ┆ 6464.5  ┆ 23788.75 │
│ 2025-07-01 ┆ 6459.25 ┆ 23580.25 │
│ 2025-07-02 ┆ 6486.25 ┆ 23736.5  │
│ 2025-07-03 ┆ 6537.25 ┆ 23964.5  │
│ 2025-07-07 ┆ 6487.5  ┆ 23779.75 │
│ 2025-07-08 ┆ 6483.25 ┆ 23792.25 │
│ 2025-07-09 ┆ 6519.75 ┆ 23954.5  │
│ 2025-07-10 ┆ 6537.25 ┆ 23913.25 │
│ 2025-07-11 ┆ 6512.25 ┆ 23857.0  │
│ 2025-07-14 ┆ 6523.5  ┆ 23936.5  │
│ 2025-07-15 ┆ 6495.75 ┆ 23958.5  │
│ 2025-07-16 ┆ 6515.5  ┆ 23979.0  │
│ 2025-07-17 ┆ 6554.0  ┆ 24160.5  │
│ 2025-07-18 ┆ 6548.0  ┆ 24132.5  │
│ 2025-07-21 ┆ 6558.5  ┆ 24255.0  │
│ 2025-07-22 ┆ 6560.5  ┆ 24134.75 │
│ 2025-07-23 ┆ 6611.75 ┆ 24222.5  │
│ 2025-07-24 ┆ 6617.0  ┆ 24291.75 │
│ 2025-07-25 ┆ 6641.5  ┆ 24337.25 │
│ 2025-07-28 ┆ 6639.0  ┆ 24410.0  │
│ 2025-07-29 ┆ 6621.75 ┆ 24369.25 │
│ 2025-07-30 ┆ 6611.75 ┆ 24399.0  │
│ 2025-07-31 ┆ 6589.0  ┆ 24278.75 │
│ 2025-08-01 ┆ 6475.5  ┆ 23778.75 │
│ 2025-08-04 ┆ 6570.0  ┆ 24207.75 │
│ 2025-08-05 ┆ 6538.25 ┆ 24036.75 │
│ 2025-08-06 ┆ 6585.5  ┆ 24339.0  │
│ 2025-08-07 ┆ 6581.0  ┆ 24415.25 │
│ 2025-08-08 ┆ 6629.5  ┆ 24641.25 │
│ 2025-08-11 ┆ 6615.25 ┆ 24562.0  │
│ 2025-08-12 ┆ 6686.25 ┆ 24874.25 │
│ 2025-08-13 ┆ 6707.25 ┆ 24883.0  │
│ 2025-08-14 ┆ 6709.0  ┆ 24866.5  │
│ 2025-08-15 ┆ 6689.5  ┆ 24735.0  │
│ 2025-08-18 ┆ 6687.25 ┆ 24728.5  │
│ 2025-08-19 ┆ 6649.25 ┆ 24387.5  │
│ 2025-08-20 ┆ 6629.25 ┆ 24236.25 │
│ 2025-08-21 ┆ 6603.5  ┆ 24128.0  │
│ 2025-08-22 ┆ 6701.5  ┆ 24491.75 │
│ 2025-08-25 ┆ 6673.0  ┆ 24417.25 │
│ 2025-08-26 ┆ 6700.75 ┆ 24514.25 │
│ 2025-08-27 ┆ 6714.75 ┆ 24553.0  │
│ 2025-08-28 ┆ 6737.0  ┆ 24698.75 │
│ 2025-08-29 ┆ 6690.75 ┆ 24379.5  │
│ 2025-09-02 ┆ 6642.0  ┆ 24185.25 │
│ 2025-09-03 ┆ 6674.75 ┆ 24366.0  │
│ 2025-09-04 ┆ 6730.0  ┆ 24593.75 │
│ 2025-09-05 ┆ 6708.25 ┆ 24610.25 │
│ 2025-09-08 ┆ 6725.25 ┆ 24730.75 │
│ 2025-09-09 ┆ 6741.5  ┆ 24807.75 │
│ 2025-09-10 ┆ 6760.0  ┆ 24811.75 │
│ 2025-09-11 ┆ 6814.5  ┆ 24957.25 │
│ 2025-09-12 ┆ 6810.25 ┆ 25056.5  │
│ 2025-09-15 ┆ 6845.25 ┆ 25262.0  │
│ 2025-09-16 ┆ 6833.25 ┆ 25232.5  │

In [19]:
# Optionally load DB prices for comparison.
db_prices = None
if INCLUDE_DB:
    tickers = [instr['symbol'] for instr in instruments]
    db_prices = load_db_prices(tickers)
    if db_prices is not None:
        print(f'DB prices loaded: {len(db_prices)} rows, columns: {db_prices.columns}')
    else:
        print('DB prices unavailable -- proceeding with IB only')

## Run quality check (Steps 1–6)

In [20]:
results = run_quality_check(
    ib_prices, db_prices,
    volume=ib_volume,
    roll_dates=ROLL_DATES,
    stale_run_threshold=STALE_THRESHOLD,
    outlier_sigma=OUTLIER_SIGMA,
    halflife=HALFLIFE,
    print_report=True,
)

============================================================
STEP 1 — STALE PRICE DETECTION
  No stale runs detected.

STEP 2 — VOLUME / LIQUIDITY GATE
  ES: 235 low-volume rows (< 10% of median daily volume)
  NQ: 235 low-volume rows (< 10% of median daily volume)
  Zero-return + low-volume overlap: 0
  Zero-return at normal volume (holidays/CBs): 0

STEP 3 — ROLL DATE CONTAMINATION
  Auto-detected probable roll/anomaly dates: 5

STEP 4 — LISTWISE VS PAIRWISE DELETION
  Total rows: 748
  Listwise rows: 744 (99.5%)
  Pairwise N CV: 0.00% (OK)

STEP 5 — COVARIANCE MATRIX COMPARISON
  Pairwise vs listwise — pairs with >1% diff: 0

  Annualised vol comparison:
    ib_pairwise  ib_listwise  pw_vs_lw_diff
ES       0.1497       0.1493         0.0003
NQ       0.2015       0.2009         0.0006

============================================================
DATA SOURCE RECOMMENDATION
--------------------------
Preferred source: IB
Reason: No DB source provided -- using IB data only.

INSTRUMENTS TO REVIEW
---------------------
ES: 3 probable roll/anomaly dates auto-detected — review and add to roll_dates if confirmed
NQ: 2 probable roll/anomaly dates auto-detected — review and add to roll_dates if confirmed

COVARIANCE MATRIX TO USE
------------------------
Method: listwise
Annualisation: 252
Effective N (listwise rows): 744

FLAGGED ISSUES
--------------
None — data looks clean.
============================================================

In [21]:
# Unpack the key artifacts.
stale   = results['stale']
rolls   = results['rolls']
deletion = results['deletion']
cov     = results['covariance']
S_final = results['S_final']    # recommended covariance matrix (pandas)
ret_final = results['ret_final']  # corresponding returns (pandas)

## Stale price runs

In [22]:
if stale['flagged_tickers']:
    print('Instruments with stale price runs:')
    for ticker, n_rows in sorted(stale['flagged_tickers'].items()):
        print(f'  {ticker}: {n_rows} flagged rows')
        for start, end, length in stale['runs'][ticker]:
            print(f'    {start} -> {end} ({length} consecutive zeros)')
else:
    print('No stale price runs detected.')

No stale price runs detected.

In [23]:
# Stale-price timeline -- all-polars: unpivot then .hvplot directly.
stale_mask = stale['stale_mask']
tickers = [c for c in stale_mask.columns if c != 'date']
if any(stale_mask[t].sum() > 0 for t in tickers):
    stale_long = (
        stale_mask
        .with_columns(
            [pl.col(t).cast(pl.Int8) for t in tickers]
            + [pl.col('date').cast(pl.Utf8)]
        )
        .unpivot(index='date', on=tickers, variable_name='instrument', value_name='stale')
    )
    stale_long.hvplot.heatmap(
        x='date', y='instrument', C='stale',
        cmap='Reds', clim=(0, 1), colorbar=False,
        width=900, height=max(200, len(tickers) * 40),
        title=f'Stale-price mask (red = zero-return run ≥ {STALE_THRESHOLD} days)',
        rot=45,
    )
else:
    print('No stale periods to plot.')

No stale periods to plot.

## Auto-detected roll / anomaly dates

In [24]:
total_auto = sum(len(v) for v in rolls['auto_detected'].values())
print(f'Auto-detected roll/anomaly dates: {total_auto} across {len(rolls["auto_detected"])} instruments')
for ticker, dates in rolls['auto_detected'].items():
    if dates:
        print(f'  {ticker}: {len(dates)} dates — {dates[:5]}{" ..." if len(dates) > 5 else ""}')

Auto-detected roll/anomaly dates: 5 across 2 instruments
  ES: 3 dates — [datetime.date(2025, 4, 4), datetime.date(2025, 4, 9), datetime.date(2025, 10, 10)]
  NQ: 2 dates — [datetime.date(2025, 4, 9), datetime.date(2025, 10, 10)]

## Correlation matrix (IB listwise)

In [25]:
if cov is not None:
    import numpy as np
    S = cov['S_ib_listwise']          # pandas from pypfopt -- convert at the plot boundary
    std = np.sqrt(np.diag(S.values))
    cm  = S / np.outer(std, std)
    cm_long = (
        pl.from_pandas(cm.reset_index().rename(columns={'index': 'instrument'}))
        .unpivot(index='instrument', variable_name='col', value_name='corr')
    )
    cm_long.hvplot.heatmap(
        x='col', y='instrument', C='corr',
        cmap='coolwarm', clim=(-1, 1), colorbar=True,
        width=500, height=450,
        title=f'Correlation matrix (IB listwise, EWM halflife={HALFLIFE}d)',
    )
else:
    print('Covariance comparison not available (pypfopt not installed).')

## Annualised vol comparison (pairwise vs listwise, IB vs DB)

In [26]:
if cov is not None:
    print(cov['vol_comparison'].round(4).to_string())
    if cov['flagged_vol_instruments']:
        print(f'\nInstruments with >5pp vol diff between pairwise and listwise: {cov["flagged_vol_instruments"]}')

    ib_pairwise  ib_listwise  pw_vs_lw_diff
ES       0.1497       0.1493         0.0003
NQ       0.2015       0.2009         0.0006

## Deletion assessment

In [27]:
print(f'Total rows:    {deletion["total_rows"]}')
print(f'Listwise rows: {deletion["listwise_rows"]} ({deletion["listwise_pct"]}%)')
print(f'Pairwise N CV: {deletion["pairwise_n_cv"]:.2%} '
      f'({"reliable" if deletion["pairwise_reliable"] else "UNRELIABLE"})')
print(f'Recommendation: {deletion["recommended_strategy"]}')

Total rows:    748
Listwise rows: 744 (99.5%)
Pairwise N CV: 0.00% (reliable)
Recommendation: listwise

In [28]:
# Per-pair N heatmap -- polars DataFrame built directly from the dict.
if deletion['pairwise_n']:
    rows = []
    for (ta, tb), n in deletion['pairwise_n'].items():
        rows += [{'x': ta, 'y': tb, 'N': float(n)},
                 {'x': tb, 'y': ta, 'N': float(n)}]
    tickers_all = sorted(set(t for pair in deletion['pairwise_n'] for t in pair))
    for t in tickers_all:
        rows.append({'x': t, 'y': t, 'N': float(deletion['total_rows'])})
    pl.DataFrame(rows).hvplot.heatmap(
        x='x', y='y', C='N',
        cmap='YlOrRd_r', colorbar=True,
        width=500, height=450,
        title='Per-pair N under pairwise deletion (lower = more data loss)',
    )